### ISSUE TITLE
Sort List > DataGrid + Search filter

### ISSUE THREAD

**Issue by Mysh3ll** [api-platform/admin#103]
Hello,

First, I managed to set up api platform admin. However the sort function does not work when I click on it. I see the url change with each click but no visual change:

[https://i.imgur.com/Po1PGXY.png](url)
[https://i.imgur.com/kcUT0z0.png](url)

And in a second time I added a search function, but when I enter text nothing is filtered:

[https://i.imgur.com/yFL2A6y.png](url)
[https://i.imgur.com/CuoVwDA.png](url)

What i'm doing wrong ?
Could someone give me a hand ?!

Best regards,

**Comment by dunglas** [comment]
1. API-side, you need to configure the OrderFilter: https://api-platform.com/docs/core/filters/#order-filter-sorting, but I don't think automatic ordering is supported in admin yet (PR welcome)
2. You need to use a search Filter: https://api-platform.com/docs/core/filters/#search-filter, you may also want to try #100

**Comment by Mysh3ll** [comment]
Thanks a lot for your reply, it works like a charm !

Now I'm going to see how to filter on multiple columns with a single search bar ;)

**Comment by diimpp** [comment]
Hello @Mysh3ll

can you share full example by any chance? How to enable  this `UserFilter` with the HydraAdmin?

Thanks.

**Comment by Mysh3ll** [comment]
Hi @diimpp ,

Of course with pleasure. Here is a piece of functional code to use the `UserFilter`:

```js
import React from 'react';
import {
    TextField,
    Datagrid,
    EditButton,
    List,
    ShowButton,
    Filter,
    EmailField,
} from 'react-admin';

export const User = (props) => {

    // Customize Filters (search bar)
    const UserFilter = (props) => (
        <Filter {...props}>
            <TextInput label="Rechercher N° Client" source="clientNumber" alwaysOn />
            <TextInput label="Ville" source="city" defaultValue="" />
        </Filter>
    );

    // Customize "Users" resource
    const users = props.resources.find(({name}) => 'users' === name);
    users.list = (props) => (
        <List {...props} filters={<UserFilter />} sort={{field: 'clientNumber', order: 'ASC'}}>
            <Datagrid>
                <TextField source="id" />
                <TextField source="clientNumber" label="N° client" />
                <TextField source="company" label="Société" />
                <TextField source="address" label="Adresse" sortable={false} />
                <TextField source="zipCode" label="Code postal" />
                <TextField source="city" label="Ville" />
                <TextField source="phone" label="Tél" sortable={false} />
                <TextField source="fax" label="Fax" sortable={false} />
                <EmailField source="email" label="Email" sortable={false} />
                {props.hasShow && <ShowButton />}
                {props.hasEdit && <EditButton />}
            </Datagrid>
        </List>
    );
};
```

Hoping to make my humble contribution ;)

**Comment by diimpp** [comment]
@Mysh3ll thank you! This really helped me.
Do you think there is an option to keep auto-generated `DataGrid` from Hydra admin and only add custom filter to admins default `List`?

But anyway, really appreciate your fast and on point answer!

**Comment by Mysh3ll** [comment]
@diimpp 

Maybe by this way:

```js
// Customize "Users" resource
    const users = props.resources.find(({name}) => 'users' === name);
    users.list = (props) => (
        <List {...props} filters={<UserFilter />} sort={{field: 'clientNumber', order: 'ASC'}}>
            <Datagrid rowStyle={postRowStyle}>
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'clientNumber'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'company'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'address'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'zipCode'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'city'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'phone'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'fax'))}
                {props.options.fieldFactory(props.options.resource.fields.find(({name}) => name === 'email'))}
                {props.hasShow && <ShowButton />}
                {props.hasEdit && <EditButton />}
            </Datagrid>
        </List>
```

**Comment by diimpp** [comment]
@Mysh3ll 
I've solved it! :)
In your example, instead of using `import { List } from 'react-admin';` I've switched it to  `import { List } from '@api-platform/admin';` (And removed `<Datagrid />`) and it loaded fields list all by  itself!

May I bother you a little bit more :) How do you attach exported  User class to the `HydraAdmin`?

For example my implementation looks like this, so I just pass `api` to my classes, but yours look different. It's probably very stupid question, but I working with react for second day.

```
 const apiDocumentationParser = (entrypoint) => parseHydraDocumentation(entrypoint)
   .then(({ api }) => {
        ResourceModifier.applyIdToProperty(api, {
           'users': {
               'city': {'source': 'name'},
               'restaurants': {'source': 'name', 'multiple': true},
           },
           'news': {
               'restaurant': {'source': 'name'},
           },
           'restaurants': {
               'owner': {'source': 'email'},
               'city': {'source': 'name'},
               'specialities': {'source': 'name', 'multiple': true},
           },
       });
   
     return { api };
     })
   ;
   
export default () => <HydraAdmin apiDocumentationParser={apiDocumentationParser} entrypoint={entrypoint} />;
```

Thanks!

**Comment by Mysh3ll** [comment]
@diimpp I have all my project at work, I'll reply on Monday.
Best regards,

**Comment by diimpp** [comment]
@Mysh3ll  I've found out your example at https://github.com/api-platform/admin/issues/108. Everything clear now. This usage example should be going into docs. :) Thanks again!
