### ISSUE TITLE
REST response must contain a data key after DELETE request

### ISSUE THREAD

**Issue by stahoos** [api-platform/admin#104]
I am using the hydraClient with a "react-admin": "2.1.1".
also, I used:

    "@api-platform/admin": "0.5.0",
    "@api-platform/api-doc-parser": "0.4.0",

When I DELETE something (api-platform return HTTP Code: 204) and I see the error:

    "REST response must contain a data key"

this error is reported, however, by the react-admin

https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/sideEffect/fetch.js#L42-L44

but it's the hydra parser that could actually handle it somehow in the api-platform admin?

**Comment by Mysh3ll** [comment]
Hi,

I have exactly the same behavior when I use the DELETE method.
I am also interested in the answer !

**Comment by soyuka** [comment]
Mhh, we should prevent this because a DELETE will always have an empty response (it's in the http spec). 

> but it's the hydra parser that could actually handle it somehow in the api-platform admin?

I guess yes, I'm not sure how though.

**Comment by k911** [comment]
Hi @stahoos, @Mysh3ll 
Could you please check if this problem occurs also using lastest codebase (master branch)?
Because I think it was fixed in #101, but patch has not been yet released.

**Comment by mauchede** [comment]
Hi @stahoos,

I will release version `0.5.1` with @k911's fix. It should fix your issue.

**Comment by k911** [comment]
@mauchede 
If you do not seen it yet, release `0.5.1` has failed: https://travis-ci.org/api-platform/admin/jobs/410757375#L526

PS. Don't you think it would be a good idea to create automatic package release from 'master' branch with version for example '@next-%commithash%' like some other js packages do?

**Comment by k911** [comment]
@dunglas @mauchede Sorry for pinging so much on vacation time, but it's almost 2 months when fix to this issue was first introduced and we still do not have tagged version with it.
