### ISSUE TITLE
Weird behavior of suggestion list on AutocompleteInput blur or after user pick an option

### ISSUE THREAD

**Issue by kamil-borecki** [api-platform/admin#117]
List of suggestions appears on autocompleteInput blur or after make response to api when user pick an option. 

We are using hydraClient 
All dependencies are up to date

![ezgif-3-f27288a310](https://user-images.githubusercontent.com/41875366/45886094-79ce5e80-bdb8-11e8-9c2a-f35ecf8e15c2.gif)

```jsx

const getNameText = object => {
  return object.name || '';
};


<ReferenceInput className={classes.inputBlock} {...rest} label="Account" source="account" reference="accounts"
                              filterToQuery={searchText => ({ name: searchText })} validate={required()}>
                <AutocompleteInput optionText={getNameText} inputValueMatcher={() => null}/>
              </ReferenceInput>
```

**Comment by alanpoulain** [comment]
Not an API Platform Admin issue but more a React Admin one. Closing.
