### ISSUE TITLE
Use admin with https://demo.api-platform.com/ not working

### ISSUE THREAD

**Issue by SkYNewZ** [api-platform/admin#119]
When I use :
```js
import React from 'react';
import { HydraAdmin } from '@api-platform/admin';
export default () => <HydraAdmin entrypoint="https://demo.api-platform.com"/>;
```
This is not working because of the wrong url `http://demo.api-platform.com/docs.jsonld` in the Link header. Got a 301 and javascript say `Failed to load http://demo.api-platform.com/docs.jsonld: Response for preflight is invalid (redirect)`. Url is not served as HTTPS

![screenshot from 2018-10-02 00-32-24](https://user-images.githubusercontent.com/26750012/46319578-cdbc1d00-c5da-11e8-8e64-55ec20fa0a46.png)

**Comment by embargo2710** [comment]
I have this issue too!

**Comment by samuelbigard** [comment]
Hi, same issue
