### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by dunglas** [api-platform/admin#125]
Now that both [Create React App](https://twitter.com/sulco/status/1057222100128329729) and React Admin have switched, we can do it too.

**Comment by krcrawford** [comment]
@dunglas Is there an expected timeline for this initiative?

**Comment by dunglas** [comment]
We're working on a new major version of Admin, but it isn't using TypeScript yet.

**Comment by alanpoulain** [comment]
Duplicated: https://github.com/api-platform/admin/issues/125.

**Comment by MarkLyck** [comment]
Why was this closed?

**Comment by alanpoulain** [comment]
The duplicated issue number was wrong.
