### ISSUE TITLE
Image/Upload customisation

### ISSUE THREAD

**Issue by darkiron** [api-platform/admin#128]
I follow the documentation for upload in api-platform:
[https://api-platform.com/docs/admin/getting-started#managing-files-and-images](https://api-platform.com/docs/admin/getting-started#managing-files-and-images)
and (for core api)
[https://api-platform.com/docs/core/file-upload](https://api-platform.com/docs/core/file-upload)

But the field contentUrl was not renderer as fileInput (with the same code)

**Comment by simonberton** [comment]
Same here, tried everything but get text input.

**Comment by Alexitdv** [comment]
Somebody fix it? Fight with that 2 days. I'm gonna die.

**Comment by alanpoulain** [comment]
See https://api-platform.com/docs/admin/file-upload/.
