### ISSUE TITLE
Admin platform does not handle server side errors

### ISSUE THREAD

**Issue by desmax** [api-platform/admin#129]
When I edit some entity and press save it goes to screen with list of entities without checking server side errors. When it actually sends the request (and receives 400 code with list of violations) it just shows "Bad request" message (and for some reason sends GET request to /contexts/ConstraintViolationList which fails with 401 code). 

What can I do to make it show server errors? (for example "email already taken")

**Comment by trsteel88** [comment]
I am also interested in how to do this.

**Comment by dunglas** [comment]
It looks like a regression. Can anyone check what happens?

**Comment by thomas-obernberger** [comment]
what do you mean by regression?

looks like it happens here
node_modules/@api-platform/admin/src/hydra/fetchHydra.js:31-34:
```
promises
  .expand(data.body, {
    base: getDocumentationUrlFromHeaders(data.response.headers),
})
```
---

this promise is rejected, jsond tries to access `https://hostname/contexts/ConstraintViolationList` -> but this returns an error `401 Unauthorized`, because its not using the initial set headers (with an Authorization header)
```
data.body:
  @context: "/contexts/ConstraintViolationList"
  @type: "ConstraintViolationList"
  hydra:description: "qualifications: Dieser Wert sollte nicht leer sein."
  hydra:title: "An error occurred"
  violations: [{…}]

base:
  https://hostname/docs.jsonld
```

---
then i tried to override XMLHttpRequest to force add the Authorization header
```
XMLHttpRequest.prototype.origOpen = XMLHttpRequest.prototype.open;
XMLHttpRequest.prototype.open   = function () {
    this.origOpen.apply(this, arguments);
    this.setRequestHeader('Authorization', `Bearer ${window.localStorage.getItem('token')}`);
};
```
(i know this is insecure code - i just implemented it for debugging..)
the request to `https://hostname/contexts/ConstraintViolationList` is working now and the promise succeeds.
.. then on line 36 the promise will be rejected with following data
```
[json[0]['http://www.w3.org/ns/hydra/core#description'][0]['@value'], status] contains:
0: "qualifications: Dieser Wert sollte nicht leer sein."
1: 400
```
-> then at line 46 the excection should be an instance of `HttpError` (`if (e instanceof HttpError) {`)
this condition is not working and instead of the previous built error message - the http error message is returned
```
content of e:
qualifications: Dieser Wert sollte nicht leer sein.
    at new HttpError (HttpError.js:56)
    at fetchHydra.js:64
```
---
i hope this information is helpful
Thanks!

**Comment by trsteel88** [comment]
@thomas-obernberger are you saying it is or isn't a regression?

Not sure if it matter, but I followed these instructions for my setup and server side errors are not handled: https://api-platform.com/docs/admin/getting-started#using-the-hydra-data-provider-directly-with-react-admin

**Comment by thomas-obernberger** [comment]
@trsteel88 i would say it should not happen this way, and there should be no request to `https://hostname/contexts/ConstraintViolationList` (correct me if i am wrong - i think i missed some specification information about hydra in my first comment)

i followed this instructions too and serverside validation errors are not handled -> no specific error message and no change to correct the data that was rejected by the server

**Comment by desmax** [comment]
@dunglas could you please have another look into this issue?

**Comment by thomas-obernberger** [comment]
@dunglas the error is not fixed, it also occurs in the new version

**Comment by Benew** [comment]
@dunglas I'm able to use custom validation contraints and the message is displayed correctly in the bottom notification (red) flashbox.
But the form's inputs are not updated accordingly.

Here is the http response :

```
{
    "@context": "/api/contexts/ConstraintViolationList",
    "@type": "ConstraintViolationList",
    "hydra:title": "An error occurred",
    "hydra:description": "weeklySlotId: Invalid weeklySlot. Day of week mismatch.",
    "violations": [
        {
            "propertyPath": "weeklySlotId",
            "message": "Invalid weeklySlot. Day of week mismatch."
        }
    ]
}
```

As an extra problem I have : I'm not able to translate validation errors independantly of oneanother.

The whole error message is getting translated, not independent violation messages / propertypaths.

**Comment by comxd** [comment]
@Benew see https://github.com/api-platform/admin/issues/157

**Comment by Dogson** [comment]
@thomas-obernberger I have the same issue where there's a request to ConstraintViolationList after a 400 error following a form submit. Have you managed to locate the cause of this behavior ?
