### ISSUE TITLE
Demo of admin against demo.api-platform.com

### ISSUE THREAD

**Issue by tacman** [api-platform/admin#13]
Is there a demo online of this anywhere?  Or a demo repo, like https://github.com/javiereguiluz/easy-admin-demo

I'm new to react (actually, I've never used it), but want to see what this looks like before setting it up.

**Comment by dunglas** [comment]
Not yet... However there are several videos in https://dunglas.fr/2017/04/api-platform-2-1-when-symfony-meets-reactjs-symfony-live-2017/

**Comment by tacman** [comment]
Yes, using 2.1 -- a tease!  Really, it looks awesome, any idea when 2.1 will be released?

**Comment by dunglas** [comment]
The frontend tools also work with 2.0! We're working hard to release a beta of 2.1.

**Comment by adamlukaszczyk** [comment]
+1 Would be great to see it in action

**Comment by dunglas** [comment]
It's in the pipe! (ping @Simperfit :D)

**Comment by Simperfit** [comment]
I'm going to do it, sorry for the delay!

**Comment by numediaweb** [comment]
@Simperfit thanks for your efforts: any updates?

**Comment by alanpoulain** [comment]
The admin demo is here: https://demo-admin.api-platform.com
