### ISSUE TITLE
Support for Mercure

### ISSUE THREAD

**Issue by dunglas** [api-platform/admin#144]
The client generator supports Mercure, but it's not yet the case of the admin. It would be a nice addition!

**Comment by dunglas** [comment]
Should use https://github.com/marmelab/react-admin/tree/master/packages/ra-realtime

**Comment by L-Luciano** [comment]
Hello,

Any news for this enchancement ?

Regards,

**Comment by andrekutianski** [comment]
This will be nice!

**Comment by dunglas** [comment]
Hi! We haven't implemented this yet but the Marmelab team provide this feature as part of the (paid) React Admin Enterprise package: https://marmelab.com/ra-enterprise/modules/ra-realtime

**Comment by alanpoulain** [comment]
Will be supported in 2.7.0.
