### ISSUE TITLE
react-admin 2.7 + overrides feature break translations 

### ISSUE THREAD

**Issue by comxd** [api-platform/admin#149]
I have tried this feature [introduced here](https://github.com/api-platform/admin/pull/130) but all translations are lost on operations (list|create|edit|show) overridden.

Confirmed with the current master branch of api-platform/admin including react-admin 2.7 (introduced by #147 ), but working good v0.6.2.

![image](https://user-images.githubusercontent.com/9022239/52989166-7a6c2f00-3402-11e9-8161-c122dd9d002a.png)

ping @jfthuillier @alanpoulain

**Comment by jfthuillier** [comment]
Hello @comxd, could you provide one of your components to reproduce this bug ?
I have tried with this component and it's working fine : https://github.com/api-platform/docs/pull/765/files#diff-2b65d65d208bdcde1eeaa917f66faf05R141

**Comment by comxd** [comment]
Sorry, finally it's not caused by the overrides feature! I used a custom layout described [here](https://github.com/marmelab/react-admin/blob/master/docs/Theming.md#customizing-the-appbar-content) , in my case I just wanted to change the default logo.
