### ISSUE TITLE
Extend Server side errors display: show list of violations

### ISSUE THREAD

**Issue by numediaweb** [api-platform/admin#157]
Is there a way to extend the message shown after a failed create resource:
![Screenshot 2019-03-15 at 15 46 46](https://user-images.githubusercontent.com/288614/54439895-fb84c080-4739-11e9-90c5-59938d58e9da.png)

Would be great to display also the full list of violations in the SnackBar Notification since we already have them in the response body:

```
{
   "@context":"\/api\/contexts\/ConstraintViolationList",
   "@type":"ConstraintViolationList",
   "hydra:title":"An error occurred",
   "hydra:description":"article: This article is already in use on that category.",
   "violations":[
      {
         "propertyPath":"code",
         "message":"article: This article is already in use on that category."
      }
   ]
}
```

**Comment by dunglas** [comment]
Good idea, it should even be the default behavior IMHO
