### ISSUE TITLE
REST response must contain a data key

### ISSUE THREAD

**Issue by brunoroux** [api-platform/admin#16]
I am using the hydraClient with an admin on rest app.
The thing is when referencing from another resource like this 
```
<ReferenceField source="productType" reference="product_types">
  <TextField source="name" />
</ReferenceField>
```
There is an error : REST response must contain a data key

**Comment by udy** [comment]
Like to understand that this message "REST response must contain a data key" means?  Your implementation is definitely looking for an object or an attribute in the header that it can't find.

I find this happen with all my CREATE, UPDATE, DELETE requests.  Any pointers will help.
