### ISSUE TITLE
Add pagination and ordering to GET_MANY_REFERENCE of hydraClient

### ISSUE THREAD

**Issue by DenisVorobyov** [api-platform/admin#162]
As long as in react-admin supports sorting and pagination in ReferenceManyField component (https://marmelab.com/react-admin/Fields.html#referencemanyfield) would be great to get it implemented in your dataProvider.

**Comment by andytson-inviqa** [comment]
Additionally filter, which is also missing from the GET_MANY_REFERENCE collectionUrl in hydraClient, which is in ReferenceManyField, essentially the same as GET_LIST but with a additional filter from the target/id

**Comment by DenisVorobyov** [comment]
One more issue here. If entities are using camel case names, then api-platform expects get requests with filters like /?yourCamelCaseFieldValue=somevalue&order[anotherCamelCaseFieldValue]=ASC.

But in the code there no conversion. 

`case GET_LIST: {
        const {
          pagination: {page, perPage},
          sort: {field, order},
        } = params;

        if (order) collectionUrl.searchParams.set(`order[${field}]`, order);
        if (page) collectionUrl.searchParams.set('page', page);
        if (perPage) collectionUrl.searchParams.set('perPage', perPage);
        if (params.filter) {
          Object.keys(params.filter).forEach(key => {
            const filterValue = params.filter[key];
            if (!isPlainObject(filterValue)) {
              collectionUrl.searchParams.set(key, params.filter[key]);
              return;
            }

            Object.keys(filterValue).forEach(subKey => {
              collectionUrl.searchParams.set(
                `${key}[${subKey}]`,
                filterValue[subKey],
              );
            });
          });
        }`

**Comment by andytson-inviqa** [comment]
@DenisVorobyov I'd suggest that be a separate ticket.
