### ISSUE TITLE
Update jsonld.js

### ISSUE THREAD

**Issue by angelo-v** [api-platform/admin#163]
Using a JSON-LD 1.1 API the following error occurs:

> Invalid JSON-LD syntax; @context property values must be strings or objects.

I experienced this elsewhere and the cause is an outdated version of jsonld.js

**Comment by dunglas** [comment]
Do you think that you could open a PR to upgrade this dependency?

**Comment by angelo-v** [comment]
The problem is rooted in api-doc-parser. The jsonld version there has already been updated, but the changes have not been released to npm (https://github.com/api-platform/api-doc-parser/issues/52)

**Comment by soyuka** [comment]
tagged so this should be fixed! Thanks for the report @angelo-v !

**Comment by angelo-v** [comment]
I think the version of the api-doc-parser has still to be  upgraded here?
