### ISSUE TITLE
Overriding cache system of hydraClient

### ISSUE THREAD

**Issue by unkndono** [api-platform/admin#170]
Hello,
First of all, thank you all for your great work at Les Tilleuls. 
I'm really glad and thankful to use your libraries in our project.

Could you advise me on some specific point?

Is there a way to change the behaviour of the cache system implemented in the hydraClient from the user land.
I'm using a standalone react admin, with a custom data provider that use your client.

Actually, my goal is to disable the cache and make my app always performs the fetches (I'm not a big fan of the optimistic rendering approach as you may notice)

I see that you export the **transformJsonLdDocumentToReactAdminDocument** from the hydraClient library.
What can I do to override that behaviour ? 

Thank you
Best regards

**Comment by alanpoulain** [comment]
Done here: https://github.com/api-platform/admin/pull/408.
