### ISSUE TITLE
Replacing custom icons using the "replaceResources" function

### ISSUE THREAD

**Issue by mrkonovalov** [api-platform/admin#174]
[docs](https://api-platform.com/docs/admin/customizing/) 

When using the "replaceResources" function, faced with a problem - it does not allow you to change the icon.

I propose to add a piece of code [after 54 lines](https://github.com/api-platform/admin/blob/master/src/docsUtils/index.js)
`
if (undefined !== replaceResource.icon) {
    resource.icon = replaceResource.icon;
}
`

This allows you to store all resource configurations in one place

**Comment by alanpoulain** [comment]
I've merged the related PR: https://github.com/api-platform/admin/pull/152.
It will be available in the next release.
