### ISSUE TITLE
The type of the "roles" attribute must be "array", "string" given.

### ISSUE THREAD

**Issue by Nykilor** [api-platform/admin#179]
So I have an entity in Api Platform that looks like that:  
			<?php

			namespace App\Entity;

			use Doctrine\ORM\Mapping as ORM;
			use Symfony\Component\Security\Core\User\UserInterface;

			/**
			 * ApiResource, config in config/api_platform/User.yaml
			 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
			 */
			class User implements UserInterface
			{
				/**
				 * @ORM\Id()
				 * @ORM\GeneratedValue()
				 * @ORM\Column(type="integer")
				 */
				private $id;

				/**
				 * @ORM\Column(type="string", length=180, unique=true)
				 */
				private $username;

				/**
				 * @ORM\Column(type="json")
				 */
				private $roles = [];

				/**
				 * @var string The hashed password
				 * @ORM\Column(type="string")
				 */
				private $password;

				public function getId(): ?int
				{
					return $this->id;
				}

				/**
				 * A visual identifier that represents this user.
				 *
				 * @see UserInterface
				 */
				public function getUsername(): string
				{
					return (string) $this->username;
				}

				public function setUsername(string $username): self
				{
					$this->username = $username;

					return $this;
				}

				/**
				 * @see UserInterface
				 */
				public function getRoles(): array
				{
					$roles = $this->roles;
					// guarantee every user at least has ROLE_USER
					$roles[] = 'ROLE_USER';

					return array_unique($roles);
				}

				public function setRoles(array $roles): self
				{
					$this->roles = $roles;

					return $this;
				}

				/**
				 * @see UserInterface
				 */
				public function getPassword(): string
				{
					return (string) $this->password;
				}

				public function setPassword(string $password): self
				{
					$this->password = $password;

					return $this;
				}

				/**
				 * @see UserInterface
				 */
				public function getSalt()
				{
					// not needed when using the "bcrypt" algorithm in security.yaml
				}

				/**
				 * @see UserInterface
				 */
				public function eraseCredentials()
				{
					// If you store any temporary, sensitive data on the user, clear it here
					// $this->plainPassword = null;
				}
			}
The `config/User.yaml`:  

			resources:
			  App\Entity\User:
				attributes:
				  access_control: is_granted('ROLE_ADMIN')
				collectionOperations:
				  get:
					method: 'GET'
				itemOperations:
				  get:
					method: 'GET'
				  delete:
					method: 'DELETE'
				  put:
					method: 'PUT'
				  post_users_register:
					method: 'POST'
					path: /users
					controller: App\Controller\RegisterUserController
					defaults:
					  _api_receive: false
					access_control_message: "Only admins can create Users"
				  auth:
					route_name: api_login
					swagger_context:
					  summary: Performs a login attempt, returning a valid token on success
					  parameters:
						- name: username
						  required: true
						  type: string
						  description: "User's username"
						- name: password
						  required: true
						  type: string
						  description: "User's password"
					  responses:
						200:
						  description: "Successful login attempt, returning a new token"
						  schema:
							type: object
							properties:
							  token:
								type: string
							  data:
								type: object
								properties:
								  id:
									type: integer
								  roles:
									type: array
									items:
									  type: string
								  username:
									type: string
						401:
						  description: "Bad credentials"
						  schema:
							type: object
							properties:
							  code:
								type: integer
								example: 401
							  message:
								type: string
								example: "Bad credentials"
					  consumes:
						- "application/json"
					  produces:
						- "application/json"

When I use the api-platform/admin it looks like that when i try to edit an entry
![react_1](https://user-images.githubusercontent.com/12702266/58556540-8dba4200-821c-11e9-897d-cd05cb75ca41.png)
![react_2](https://user-images.githubusercontent.com/12702266/58556541-8dba4200-821c-11e9-9f20-aec0eb7223ee.png)

The docs that i get for this class look like this:  
  
		{
					"@id": "#User",
					"@type": "hydra:Class",
					"rdfs:label": "User",
					"hydra:title": "User",
					"hydra:supportedProperty": [
						{
							"@type": "hydra:SupportedProperty",
							"hydra:property": {
								"@id": "#User/username",
								"@type": "rdf:Property",
								"rdfs:label": "username",
								"domain": "#User",
								"range": "xmls:string"
							},
							"hydra:title": "username",
							"hydra:required": false,
							"hydra:readable": true,
							"hydra:writable": true
						},
						{
							"@type": "hydra:SupportedProperty",
							"hydra:property": {
								"@id": "#User/roles",
								"@type": "rdf:Property",
								"rdfs:label": "roles",
								"domain": "#User"
							},
							"hydra:title": "roles",
							"hydra:required": false,
							"hydra:readable": true,
							"hydra:writable": true
						},
						{
							"@type": "hydra:SupportedProperty",
							"hydra:property": {
								"@id": "#User/password",
								"@type": "rdf:Property",
								"rdfs:label": "password",
								"domain": "#User",
								"range": "xmls:string"
							},
							"hydra:title": "password",
							"hydra:required": false,
							"hydra:readable": true,
							"hydra:writable": true,
							"hydra:description": "The hashed password"
						},
						{
							"@type": "hydra:SupportedProperty",
							"hydra:property": {
								"@id": "#User/salt",
								"@type": "hydra:Link",
								"rdfs:label": "salt",
								"domain": "#User"
							},
							"hydra:title": "salt",
							"hydra:required": false,
							"hydra:readable": true,
							"hydra:writable": false
						}
					],
					"hydra:supportedOperation": [
						{
							"@type": [
								"hydra:Operation",
								"schema:FindAction"
							],
							"hydra:method": "GET",
							"hydra:title": "Retrieves User resource.",
							"rdfs:label": "Retrieves User resource.",
							"returns": "#User"
						},
						{
							"@type": [
								"hydra:Operation",
								"schema:DeleteAction"
							],
							"hydra:method": "DELETE",
							"hydra:title": "Deletes the User resource.",
							"rdfs:label": "Deletes the User resource.",
							"returns": "owl:Nothing"
						},
						{
							"@type": [
								"hydra:Operation",
								"schema:ReplaceAction"
							],
							"expects": "#User",
							"hydra:method": "PUT",
							"hydra:title": "Replaces the User resource.",
							"rdfs:label": "Replaces the User resource.",
							"returns": "#User"
						},
						{
							"@type": [
								"hydra:Operation",
								"schema:CreateAction"
							],
							"expects": "#User",
							"hydra:method": "POST",
							"hydra:title": "Creates a User resource.",
							"rdfs:label": "Creates a User resource.",
							"returns": "#User"
						},
						{
							"@type": [
								"hydra:Operation",
								"schema:CreateAction"
							],
							"expects": "#User",
							"hydra:method": "POST",
							"hydra:title": "Creates a User resource.",
							"rdfs:label": "Creates a User resource.",
							"returns": "#User"
						}
					],
					"hydra:description": "ApiResource, config in config/api_platform/User.yaml"
				},

And when I try to edit the entity I get `The type of the "roles" attribute must be "array", "string" given.`. Dosn't matter what i type into that field.
I'm using the latest Api Platform and the latest Api Platofrm Admin. Anyone has an idea why is this happening? I have the same issue with other entities that I use in my project that use `json`/`array` ORM type.

The server code that i use is avaliable at: https://github.com/Nykilor/telefony-srv

**Comment by comxd** [comment]
You need to make a string to array conversion at the RA application before send the request to the API. You can easily use an [ArrayInput](https://marmelab.com/react-admin/Inputs.html#arrayinput) component for that.

**Comment by Nykilor** [comment]
So I resolved this issue, there are two ways first is if the pull request of mine goes trough: https://github.com/api-platform/core/pull/2840  
Second is just to edit the field by yourself by using the https://api-platform.com/docs/admin/getting-started/#customizing-the-admin example as a template and instead of the <RichTextField> component using the (for input only not the field):

			<ArrayInput  {...props}>
			  <SimpleFormIterator>
				<TextInput />
			  </SimpleFormIterator>
			</ArrayInput>

**Comment by ldbglobe** [comment]
A simple solution is to override JsonLd Context using anotation in your Api-Platform Entity

```
    /**
     * @ORM\Column(type="simple_array")
     * @ApiProperty(
     *     attributes={
     *         "jsonld_context"={
     *             "@type"="http://www.w3.org/2001/XMLSchema#array",
     *         }
     *     }
     * )
     */
    private $my_simple_array_field= [];
```

**Comment by davispuh** [comment]
I've exactly same issue, why this still haven't been fixed...

@ldbglobe that workaround works great, thanks!

**Comment by knarficious** [comment]
@ldbglobe Thank you, that works fine
