### ISSUE TITLE
JWT Authentication Support does not work

### ISSUE THREAD

**Issue by jjpeleato** [api-platform/admin#185]
| Q                 | A
| ----------------- | ---
| Issue Type        | Issue
| Admin Version  | v0.6.3
| Solution | Downgrade to v0.6.2
| Local Machine OS  | Ubuntu 18.04 (but shouldn't be relevant in this case)

### Description

Hello!

I have detected a problem with version 0.6.3 related to JWT Authentication.

When you login correctly and the process of loading all entities is done to map the fields, the Authorization: Bearer [token] header is not sent and generates an error 401 Invalid JWT Token.

`Failed to load resource: the server responded to a status of 401`

In other calls if it is sent, for example, in the call Request Method: OPTIONS.

I validated the JWT token in https://jwt.io/ in case there was an error, but it is a valid token. I used token in Swagger and it has worked correctly.

The solution I have found is to downgrade to v0.6.2.

### package.json file

```
{
    "name": "admin-component",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@api-platform/admin": "0.6.3",
        "react": "^16.8.6",
        "react-dom": "^16.8.6",
        "react-scripts": "3.0.1"
    },
    "devDependencies": {
        "dotenv-cli": "^2.0.0"
    },
    "scripts": {
        "start": "react-scripts start",
        "build:pro": "react-scripts build",
        "build:dev": "dotenv -e .env.development.local react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
    },
    "eslintConfig": {
        "extends": "react-app"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    }
}
```

If you need more information, ask me.

Grettings @jjpeleato.

**Comment by nietzscheson** [comment]
Confirm!

**Comment by fri0z** [comment]
I have exactly the same problem. The roll back to 0.6.2 helped.

**Comment by dunglas** [comment]
FYI, we're working with @marmelab on a brand new version of API Platform Admin. It is almost ready, and will improve a lot the authentication part.

**Comment by jjpeleato** [comment]
> 
> 
> FYI, we're working with @marmelab on a brand new version of API Platform Admin. It is almost ready, and will improve a lot the authentication part.

Cool! It is a good news.

I knowing the information. You can close the thread if you think it is necessary.

Thank you.

**Comment by shehi** [comment]
Confirming this problem here as well.

**Comment by kamyp** [comment]
I have same problem. I have try to downgrade to 0.6.2 but the error is always here.
I have the installation of api platform after install Symfony 4 and i'm in local !
All endpoints works with postman and my token is all right !
Any ideas to help me ? Thx

[sceen](https://user-images.githubusercontent.com/45363608/61000377-9181ce00-a35d-11e9-9a1f-8b77a250549c.PNG)

**Comment by Rebolon** [comment]
i opened a thread in StackOverflow about this (and i really had a big headache when i faced the problem) https://stackoverflow.com/questions/57184540/react-admin-how-to-use-basic-authentification-in-my-sample-auth-headers-are-w/57217309#57217309
Thx for the solution

**Comment by fri0z** [comment]
@Rebolon great job

**Comment by shehi** [comment]
There is solution?!

**Comment by fri0z** [comment]
This is a temporary solution

**Comment by vdwijngaert** [comment]
The funny part is that it works in dev mode, but not in a production build. 

Not sure why, but not storing the auth headers in a const (like the docs say), fixes the problem for me. Eg:

```javascript
const fetchHydra = (url, options = {}) => baseFetchHydra(url, {
  ...options,
  headers: new Headers({
    'Authorization': `Bearer ${localStorage.getItem('token')}`,
  }),
});

const apiDocParser = entrypoint => parseHydraDocumentation(entrypoint, {
  headers: new Headers({
    'Authorization': `Bearer ${localStorage.getItem('token')}`,
  }),
...
```

**Comment by lukebee** [comment]
Any news on this?

**Comment by pgnewikow** [comment]
it still doesn't work in 1.0.0

**Comment by tienvx** [comment]
Guys! please test again with version 1.0.1

A few notes:
* There is an example for authentication support at https://api-platform.com/docs/admin/authentication-support/
* You may need to move your custom code from api documentation parser to new resource guessers https://api-platform.com/docs/admin/customizing/

**Comment by Tulis2** [comment]
Thanks a million. Waited for this for a long time. It's working in v1.0.1 :)

**Comment by alanpoulain** [comment]
Great job @tienvx! I think we can close this issue then.
