### ISSUE TITLE
Trying to get started

### ISSUE THREAD

**Issue by dmeziere** [api-platform/admin#19]
Hello,

I tried to follow the Getting started instructions, but I got the following in the term :
`export 'default' (imported as 'HydraAdmin') was not found in 'api-platform-admin'`

In the JS console, I also have :
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at App.js:6.
    in App (at index.js:7)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.`

Does someone have a solution ?

**Comment by dunglas** [comment]
It's a docs issue. I fixed it in af8cca57558ff47808d7347f388c61eb9052a88d. Can you confirm it fixes tour problem @dmeziere?

**Comment by dmeziere** [comment]
It works like a charm ! Thank you ! This Hydra admin looks really sexy ! I have to figure out how to authenticate the user to api-platform and handle it's authorizations from the front, but it is out of scope.
