### ISSUE TITLE
Migrate the library to TypeScript

### ISSUE THREAD

**Issue by dunglas** [api-platform/admin#230]
As React Admin migrated to TypeScript, we should migrate API Platform Admin too. PropTypes definitions must be kept for consumer applications not written in TS.

**Comment by instalab** [comment]
I think I'll claim this task if possible.
I've been working on a bigger JS React projects at work and would like to learn TypeScript now.

**Comment by instalab** [comment]
@dunglas Any additional notes you'd like to add, feel free ;)

**Comment by instalab** [comment]
OK just a note from myself, the guys from React Admin haven't migrated fully yet.

**Comment by instalab** [comment]
@dunglas Do you have Slack?
Could I join if you do?

**Comment by dunglas** [comment]
@instalab We do! https://api-platform.com/support/

**Comment by pierre-H** [comment]
Any news ? 😃

**Comment by dunglas** [comment]
@pierre-H AFAIK no one is currently working on this.

**Comment by Fabious** [comment]
I'm working on it, expect a PR soon 😉
