### ISSUE TITLE
Initial locale is not passed down (as well as customReducers, customSagas etc..)

### ISSUE THREAD

**Issue by DenisVorobyov** [api-platform/admin#234]
As in the HydraAdmin component store is created explicitly, please add all parameters (including locale).

For example:
<HydraAdmin
            entrypoint={process.env.REACT_APP_API_ENTRYPOINT}
            locale={resolveBrowserLocale()}
 / >

Regardless what is user's locale is - "en" will be in the store.

I think the issue is here:

const HydraAdmin = ({
  entrypoint,
  dataProvider = dataProviderFactory(entrypoint),
  i18nProvider,
  authProvider,
  ...rest
}) => (
  <Provider
    store={createAdminStore({
      authProvider,
      dataProvider,
      i18nProvider,
      history,
    })}>
    <AdminGuesser
      dataProvider={dataProvider}
      authProvider={authProvider}
      history={history}
      i18nProvider={i18nProvider}
      {...rest}
    />

Which should be like the following:

const HydraAdmin = ({
  entrypoint,
  dataProvider = dataProviderFactory(entrypoint),
  i18nProvider,
  authProvider,
 customReducers,
      customSagas,
      locale,
  ...rest
}) => (
  <Provider
    store={createAdminStore({
      authProvider,
      dataProvider,
      i18nProvider,
      history,
      customReducers,
      customSagas,
      locale,
    })}>
    <AdminGuesser
      dataProvider={dataProvider}
      authProvider={authProvider}
      history={history}
      i18nProvider={i18nProvider}
       customReducers={customReducers}
      customSagas={customSagas}
      locale={locale}
      {...rest}
    />

**Comment by dunglas** [comment]
Good idea. Would you want to open a Pull Request?

**Comment by tienvx** [comment]
Thanks for figuring it out @DenisVorobyov . Your suggestion helped me fixing issue when the [Configuration](https://marmelab.com/react-admin-demo/#/configuration) can not be changed. I need it so bad so I created a Pull Request. Sorry for stealing your works :D

**Comment by mleczakm** [comment]
There is same problem with `history` (there is no way to use `browserHistory` instead of hash-based one), but looks like it is not fully supported in RA anyway (can't get it working on rowClick action, edit/show etc links work great).

**Comment by alanpoulain** [comment]
Done in 2.0.
