### ISSUE TITLE
how to use with Gatsby

### ISSUE THREAD

**Issue by BernardA** [api-platform/admin#244]
Is is at all possible to use the Admin component with Gatsby?

I attempted very naively to set it up as if it was just another Gatsby page but of course it threw all sorts of errors. 

Note that for this app, the front-end is Gatsby while the API is, of course, API-Platform,

Just for the record it was like so on my Gatsby application:

`/src/pages/admin.js`

      import React from 'react';
      import { HydraAdmin } from '@api-platform/admin';
      import PropTypes from 'prop-types';
      import Layout from '../components/layout';
      import SEO from '../components/seo';

      const Admin = () => <HydraAdmin entrypoint="http://127.0.0.1:8000/api" />;

     export default () => {
        return (
            <Layout>
                <SEO title="Admin" />
               <Admin />
           </Layout>
      );
     };

**Comment by dunglas** [comment]
Can you copy the errors?

**Comment by BernardA** [comment]
It was a long list of errors, though they seem related to the same package.

I did notice some mismatches when npm installing `@api-platform/admin`, as follows:
`react` and `react-dom` on my package.json is 16.9.0 while it seems to require 16.0.0 to 16.4.0

If the above are breaking changes that in may explain below.

After running `gatsby develop` ( showing first error only)


       ERROR  Failed to compile with 33 errors                                                                                                                        10:07:29 AM
      This dependency was not found:
       * @babel/runtime/helpers/builtin/interopRequireDefault in ./node_modules/ra-ui-materialui/node_modules/@material-ui/icons/FilterList.js, ./node_modules/ra-ui-materialui/node_modules/@material-ui/icons/ExpandMore.js and 31 others
      To install it, you can run: npm install --save @babel/runtime/helpers/builtin/interopRequireDefault
     ✖ ｢wdm｣:
     ERROR in ./node_modules/ra-ui-materialui/node_modules/@material-ui/icons/FilterList.js
     Module not found: Error: Can't resolve '@babel/runtime/helpers/builtin/interopRequireDefault' in '/Users/bernardo/Sites/quiamo/node_modules/ra-ui-materialui/node_modules/@material-ui/icons'
      @ ./node_modules/ra-ui-materialui/node_modules/@material-ui/icons/FilterList.js 3:29-92
      @ ./node_modules/ra-ui-materialui/esm/list/FilterButton.js
      @ ./node_modules/ra-ui-materialui/esm/list/index.js
      @ ./node_modules/ra-ui-materialui/esm/index.js
      @ ./node_modules/react-admin/esm/index.js
      @ ./node_modules/@api-platform/admin/lib/FieldGuesser.js
     @ ./node_modules/@api-platform/admin/lib/index.js
     @ ./src/pages/admin.js
     @ ./.cache/sync-requires.js
      @ ./.cache/app.js
      @ multi ./node_modules/event-source-polyfill/src/eventsource.js (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app

When I attempted to install `npm install --save @babel/runtime/helpers/builtin/interopRequireDefault` I got the error:

     npm ERR! code ENOLOCAL
     npm ERR! Could not install from "@babel/runtime/helpers/builtin/interopRequireDefault" as it does not contain a package.json file.

**Comment by partoa** [comment]
@BernardA Were you ever able to figure this out?

**Comment by BernardA** [comment]
Well, kind of.
I believe I understood the set up but then I end up with [another issue](https://github.com/api-platform/admin/issues/254).

As you may have noticed, it seems that nobody is reviewing the open issues in this repository. As per this one, It's been there for a while already without any intervention.

**Comment by partoa** [comment]
Yeah... Very nifty tool. A good community behind it would be very interesting.

**Comment by BernardA** [comment]
@partoa, just to clarify the set up used on the [other issue](https://github.com/api-platform/admin/issues/254).
Given the above issue within Gatsby, there I chose NOT to use `api-platform-admin` within Gatsby but rather to create another app, exclusively dedicated to admin. It would sit in another domain or in a sub-domain. That is a valid alternative, depending on the set up.

**Comment by partoa** [comment]
We may end up doing the same exact thing. We need something similar, I suspect.

**Comment by BernardA** [comment]
Sure. As you may be aware, API-Platform-admin is wrapped around react-admin. 
So, one obvious alternative is to skip API-Platform-admin altogether and go directly for react-admin. 
There again you can use it in-app or as a separated, dedicated app.

The only hiccup is that one needs to use a data provider to connect react-admin to API-Platform. This is what API-Platform-admin provides what out the box. As it seems that a separate data provider for API-Platform is not available, one would have to create it. 
I am not there at this point, but may be forced to get there if there is no alternative. Let me know how it goes for you.

**Comment by partoa** [comment]
Will do. Thanks.
