### ISSUE TITLE
[BUG] object id being reassigned as iri is breaking edits

### ISSUE THREAD

**Issue by jspizziri** [api-platform/admin#259]
**Admin version(s) affected**: 1.0.2

**Description**  
The id reassignment of `@id` to `id` in [the constructor of the ReactAdminDocument](https://github.com/api-platform/admin/blob/master/src/hydra/dataProvider.js#L17) is resulting in edits being impossible. The issue is that this constructor results in mapping this:

```json
{
  "@context": "/contexts/Foo",
  ​​"@id": "/api/foos/1",
  "@type": "Foo",
  "id": 1,
  "​​name": "Bar Baz"
}
```

To this:
```json
{
  "@context": "/contexts/Foo",
  ​​"@id": "/api/foos/1",
  "@type": "Foo",
  "id": "/api/foos/1",
  "originId": 1,
  "​​name": "Bar Baz"
}
```

Subsequently, when the EditGuesser, and InputGuesser construct the input fields for this document, it correctly assess the type of the `id` field as a `number`, but then sets the value to the IRI string. So you get the following:

```html
<input 
  aria-invalid="false" 
  class="MuiInput-input-272 MuiInput-inputType-275" 
  id="id" 
  name="id" 
  type="number" 
  value="/api/foos/1"
>
```

Firstly this breaks the input, as no id actually shows up in the UI (number inputs can't parse strings), and secondly when attempting to save the form you get an error from the API saying there's a type mismatch, as it's expecting an int id, but received a string.

**How to reproduce**  
Spin up the api-platform, and attempt to edit a document in admin which has an integer id.

**Possible Solution**  
The obvious option seems to be to not reassign the id field; however, I'm assuming that was implemented for a reason, and its removal would cause regressions elsewhere. Apart from that it would probably be required to add some conditional logic to the `InputGuesser` so that `if (field.name === 'id') { value = field.originId }`.

**Additional Context**  
You can work around this issue by manually copying the resources id and entering into the id field, then saving. However, that's clearly not a sustainable solution.

**Comment by Moutard3** [comment]
Got a problem similar with a Uuid typed Id

```json
{
  "@context": "/contexts/User",
  "@id": "/users/002c9895-ecea-4f50-8d01-e6634cfaba17",
  "@type": "User",
  "email": "user@email.tld",
  "originId": null,
  "id": "/users/002c9895-ecea-4f50-8d01-e6634cfaba17",
  "password": "password"
}
```

`id` can't be converted to Uuid and throw an error.

**Comment by Perni1984** [comment]
@jspizziri @Moutard3 did you find any workaround for this, I am running into the same problem now.
