### ISSUE TITLE
Range filter changes [] style to dot notation

### ISSUE THREAD

**Issue by DenisVorobyov** [api-platform/admin#260]
If use standard filters to achieve range filter functionality, i.e.:
```
<Filter {...props}>
    <SelectInput
        source='year[gte]'
        label="Year from"
        choices={getYears()}
        alwaysOn
    />
</Filter>
```
as a result you will get api request: year.gte=2002 instead of required year[gte]=2002

**Comment by anegve** [comment]
+1
I have the same behavior

**Comment by DenisVorobyov** [comment]
Temporary solution (which i have done) can be to write custom filter (extending ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\RangeFilter) and replace square brackets with for example curly ones:

```
<Filter {...props}>
    <SelectInput
        source='year{gte}'
        label="Year from"
        choices={getYears()}
        alwaysOn
    />
</Filter>
```

`
protected function filterProperty(string $property, $values, QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        if (1 === preg_match('/(.*){(.*)}/',$property, $matches)) {
            $property = $matches[1];
            $values = [$matches[2] => $values];
        }

        parent::filterProperty($property, $values, $queryBuilder, $queryNameGenerator, $resourceClass, $operationName);
    }`

**Comment by anegve** [comment]
Not the best solution, but works)
Thank you @DenisVorobyov
