### ISSUE TITLE
docs.jsonld fetching over http instead of https

### ISSUE THREAD

**Issue by Rahulshahare** [api-platform/admin#262]
**API Platform version(s) affected**: x.y.z

**Description**  
Hydra Entry Point URL is provided with https protocol which is (entrypoint:"https://bookshop.srrstechnologies.ml/api") , Hitting Api Producing Entypoint for Entities but docs.jsonld requesting over http. the convertion of https to http seems like error to me.

admin hosted on (github)[https://rahulshahare.github.io/api-platform-admin]

![Screenshot (27)](https://user-images.githubusercontent.com/13538433/70596356-b54a8800-1c0b-11ea-97dc-bcc09d84a707.png)
![Screenshot (28)](https://user-images.githubusercontent.com/13538433/70596361-b8457880-1c0b-11ea-8851-76aa4a9a0d09.png)

And Now Same Error While Hosting on same domain
API : https://bookshop.srrstechnologies.ml/api
ADMIN : https://bookshop.srrstechnologies.ml/admin/
![Screenshot (29)](https://user-images.githubusercontent.com/13538433/70596671-70732100-1c0c-11ea-98f6-4e2574a93f59.png)

**#live site over non-https** 
[admin](http://bookshop.srrstechnologies.ml/admin-http/)
![Screenshot (40)](https://user-images.githubusercontent.com/13538433/70657892-cc788c80-1c82-11ea-8b48-b10e058f6829.png)

**Comment by Rahulshahare** [comment]
Hosting Admin and API on same Domain

**Comment by Rahulshahare** [comment]
site is li e on non htttps. i think its an error over https

**Comment by tienvx** [comment]
I having this issue too. But I fixed it. This is **not a bug** of API Platform.

Here is what happen:
* If you look at the request https://bookshop.srrstechnologies.ml/api on your browser's console, you can see an item from response's header: `link: <http://bookshop.srrstechnologies.ml/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"`. The problem is the schema. It must be `https`, not `http`
* This is the issue why the schema is http, not https https://github.com/symfony/symfony/issues/17072
* The reason is the environment variable `TRUSTED_PROXIES` is missing from api container. Set its value to `127.0.0.1,REMOTE_ADDR` fixed the problem for me

How to fix:
* Add `TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR` to `.env` and deploy again
* Or if you are using Kubernetes, you can run this command `kubectl set env deployment/api TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR -n namespace`

I think the solution is **not safe**, because you trusted all proxies. Please find the correct ip of your proxy.

**Comment by Domopus** [comment]
Hi,

I exactly had the same problem and @tienvx solution solved it. Thanks a lot!

I see it's not the best solution because it's not safe but I don't have a very good understanding of proxies and what could possibly be done. What should I do to make it safer?

Thanks in advance

**Comment by Rahulshahare** [comment]
Yes guys it's a Issue of TRUSTED PROXIES Variable in environment file. 
#IssueClosed

**Comment by ZeeCoder** [comment]
> I having this issue too. But I fixed it. This is **not a bug** of API Platform.
> 
> Here is what happen:
> 
> * If you look at the request https://bookshop.srrstechnologies.ml/api on your browser's console, you can see an item from response's header: `link: <http://bookshop.srrstechnologies.ml/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"`. The problem is the schema. It must be `https`, not `http`
> * This is the issue why the schema is http, not https [symfony/symfony#17072](https://github.com/symfony/symfony/issues/17072)
> * The reason is the environment variable `TRUSTED_PROXIES` is missing from api container. Set its value to `127.0.0.1,REMOTE_ADDR` fixed the problem for me
> 
> How to fix:
> 
> * Add `TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR` to `.env` and deploy again
> * Or if you are using Kubernetes, you can run this command `kubectl set env deployment/api TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR -n namespace`
> 
> I think the solution is **not safe**, because you trusted all proxies. Please find the correct ip of your proxy.

I would've NEVER guessed this, and I've been looking for the bug in api-platform's admin bundle for hours...
Thanks @tienvx  🙏

**Comment by awsMultitec** [comment]
Hello ! 
I have follow your solution because i have the same problem, I deployed in AWS ( ECS for api and react in S3 + Cloudfront) but I still receive  http instead of https, Is there any solution for this ? thank you !!

**Comment by DennisdeBest** [comment]
I had the same problem running the admin in Next and serving the API through nGinx. 
I use it in Kubernetes Pods with Traefik as the Ingress.

To fix this I added `HTTPS=true` to the env variables in my helm chart.

```yaml
    images:
        php:
            env:
                -   name: HTTPS
                    value: "true"
```

This also works if you set it directly on the server inside a `.env.local` file.

**Comment by tienvx** [comment]
@DennisdeBest I tried your solution and it work for me. Weird  I can't find any document related to this `HTTPS` environment variable. Checking the code and it seems the correct values for it should be `on|off`
