### ISSUE TITLE
CORS error on docs.jsonld

### ISSUE THREAD

**Issue by BernardA** [api-platform/admin#264]
**API Platform version(s) affected**:"@api-platform/admin": "^1.0.2"

**Description**  
It's able to access `/api` route and retrieve info but fails to access route `/api/docs.jsonld` throwing CORS error.

**How to reproduce**  
Full code [in this repository](https://github.com/BernardA/quiamo-api), but in summary: 

The API is running at PHP serve `php -S 127.0.0.1:8001 -t public`, while the admin is running on 
`http://localhost:3000/`

/config/packages/nelmio_cors.yaml

     nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://localhost:[0-9]+.*|127.0.0.1(:[0-9]+)?']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition','Link','X-Total-Count']
        max_age: 3600
    paths:
        '^/': ~

**Possible Solution**  

**Additional Context**  
This is the output of the `/api` call, than happens immediately before calling `/api/docs.jsonld`
![Screenshot 2020-01-12 at 3 36 56 PM](https://user-images.githubusercontent.com/9449665/72220505-83ea1280-3551-11ea-93c5-8d1c83bb0086.png)

These are the headers for the `/api/docs.jsonld` request:

![Screenshot 2020-01-12 at 3 38 38 PM](https://user-images.githubusercontent.com/9449665/72220516-b3008400-3551-11ea-821e-a7cb71c0f110.png)

The full error output on console:

![Screenshot 2020-01-12 at 3 40 09 PM](https://user-images.githubusercontent.com/9449665/72220539-e6dba980-3551-11ea-9227-a5c60b9d3474.png)

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/admin/issues/73.

**Comment by BernardA** [comment]
Well, I tried pretty much everything on that issue and I still have the same problem.

If I look on the output of the server it shows:
`127.0.0.1:51230 [404]: /api/docs.jsonld - No such file or directory`.

That makes sense, as there's not really a `docs.jsonld` directory/file. At least not one that is visible.

**Comment by alanpoulain** [comment]
This is not related to this project. You can add your issue to core project but I don't think it's a real issue (probably something is not configured correctly).

**Comment by BernardA** [comment]
API-platform seems to work fine except for requests coming from API-platform/Admin. As you say, it may be a configuration problem, but it is a problem that a bunch of people are having and seems to be  specific for `/admin` docs request.  

One would expect the configuration to be less finicky or, if that's not the case, at least have a  documentation to guide people. It's clear this is not trivial.

**Comment by BernardA** [comment]
My last attempt was changing the server. I was using the PHP server as
`php -S 127.0.0.1:8001 -t public`.
I installed the [Symfony binary](https://symfony.com/download)  with `curl -sS https://get.symfony.com/cli/installer | bash` and finally run `symfony server:start`.

It works fine now. Not sure what the problem is though. 
I would suggest your docs to advise not to user the PHP server. That would save people a lot of pain.

**Comment by baspeeters** [comment]
@BernardA Your solution worked for me, thanks!
