### ISSUE TITLE
Notification error from server doesn't work correct

### ISSUE THREAD

**Issue by pavel-nano** [api-platform/admin#274]
I have a problem with show notification from my api.
The notification red block doesn't show after form submit.
I made a video with my problem https://yadi.sk/i/3AmC1d_Da0CNuA

The problem in "@api-platform/admin": "^2.0.1".
I used "@api-platform/admin": "0.6" and there I don't had this problem.

**Comment by L-Luciano** [comment]
Hi,

The same for me.

Up.

Regards

**Comment by L-Luciano** [comment]
Any news ?

**Comment by alanpoulain** [comment]
Does it work with the new version? Closing for now, feel free to reopen.
