### ISSUE TITLE
JWT token issue in HTTP Header

### ISSUE THREAD

**Issue by sunglee** [api-platform/admin#275]
**API Platform version(s) affected**: 2.5.4 with `api-platform/admin` version 2.0.1

**Description**  
When using JWT authentication, authorization header value is not set properly.

**How to reproduce**  
Here is the code I use. Basically copied from https://api-platform.com/docs/admin/authentication-support/.

```
// App.js
import React from "react";
import {Redirect, Route} from "react-router-dom";
import {
  fetchHydra as baseFetchHydra,
  HydraAdmin,
  hydraDataProvider as baseHydraDataProvider,
  ResourceGuesser
} from "@api-platform/admin";
import parseHydraDocumentation from "@api-platform/api-doc-parser/lib/hydra/parseHydraDocumentation";

const entrypoint = process.env.REACT_APP_API_ENTRYPOINT;
const fetchHeaders = { Authorization: `Bearer ${window.localStorage.getItem("token")}` };
const fetchHydra = (url, options = {}) => baseFetchHydra(url, {
  ...options,
  headers: new Headers(fetchHeaders),
});
const apiDocumentationParser = entrypoint => parseHydraDocumentation(entrypoint, {headers: new Headers(fetchHeaders)})
  .then(
    ({api}) => ({api}),
    (result) => {
      switch (result.status) {
        case 401:
          return Promise.resolve({
            api: result.api,
            customRoutes: [
              <Route path="/" render={() => {
                window.localStorage.getItem("token") ? window.location.reload() : <Redirect to="/login" />
              }} />
            ],
          });

        default:
          return Promise.reject(result);
      }
    },
  );
const dataProvider = baseHydraDataProvider(entrypoint, fetchHydra, apiDocumentationParser);
const authProvider = {
  login: ({username, password}) => {
    const request = new Request(entrypoint + '/login', {
      method: 'POST',
      body: JSON.stringify({"email": username, password}),
      headers: new Headers({'Content-Type': 'application/json'}),
    });
    return fetch(request)
      .then(response => {
        if (response.status < 200 || response.status >= 300) {
          throw new Error(response.statusText);
        }
        return response.json();
      })
      .then(({token}) => {
        window.localStorage.setItem('token', token);
      });
  },
  logout: () => {
    localStorage.removeItem('token');
    return Promise.resolve();
  },
  checkAuth: () => {
    return localStorage.getItem('token') ? Promise.resolve() : Promise.reject();
  },
  checkError: error => {
    const status = error.status;
    if (status === 401 || status === 403) {
      localStorage.removeItem('token');
      return Promise.reject();
    }
    return Promise.resolve();
  },
  getPermissions: params => Promise.resolve(),
};

export default () => (
  <HydraAdmin
    authProvider={authProvider}
    entrypoint={entrypoint}
    dataProvider={dataProvider}
  >
    <ResourceGuesser name="ad_campaigns" />
  </HydraAdmin>
);
```

### Issue 1. Before Authentication

**Expected**
As we don't have JWT token in localStorage, redirecting to `/login` page is expected.

**Actual**
Gives 403 error from sending `{Authorization: Bearer null}` Headers
![Screen Shot 2020-02-19 at 9 51 30 AM](https://user-images.githubusercontent.com/38310/74862414-f42e4580-5300-11ea-9be9-6a5b4c9653a8.png)

**Possible Solution**  
Update `fetchHeaders` variable like this.
```
// old
const fetchHeaders = { Authorization: `Bearer ${window.localStorage.getItem("token")}` };
// new
const fetchHeaders = () => {
  if (window.localStorage.getItem("token")) {
    return {Authorization: `Bearer ${window.localStorage.getItem("token")}`};
  }
  return {}
}
```

### Issue 2. Failure After Successful Login
After updating `fetchHeaders` variable like above, a user can see login page when localStorage token is not available. When a user login with valid credential, there comes a multiple api calls with errors.

Screenshot of login api success. It returns Response with new token value.
<img width="1524" alt="Screen Shot 2020-02-19 at 12 55 06 PM" src="https://user-images.githubusercontent.com/38310/74875452-20ed5780-5317-11ea-9da9-78d6e2f50c32.png">

Screenshot of one of api call with valid Authorization token.
<img width="1524" alt="Screen Shot 2020-02-19 at 12 55 13 PM" src="https://user-images.githubusercontent.com/38310/74875585-5c882180-5317-11ea-8d0b-9dc967f802e6.png">

Screenshot of api call failure
<img width="1524" alt="Screen Shot 2020-02-19 at 12 55 19 PM" src="https://user-images.githubusercontent.com/38310/74875725-9527fb00-5317-11ea-8399-c8ef8a78c704.png">

In my example, there are four calls of `ad_campaigns` api after login success. One of them is success and other three are failure which gives `Unhandled Rejection (Error): Unreachable resource` page error.

I am not sure why there are four api calls for one entity after login. And why three of them are not sending Authorization Headers even if localStorage has token value.

**Comment by remigarcia** [comment]
Same problem here. Followed the doc for authProvider and dataProvider, I have the same problem as you. I was in version 1.0.2, upgraded to 2.0.2, problem is the same.

**Comment by wcoppens** [comment]
Same problem here, someone found a solution already?

**Comment by mwencelis** [comment]
Same problem here - Issue 2
api-platform/admin@2.2.1
I also followed the doc for authProvider and dataProvider and I think that doc example is buggy.

it seems that the parseHydraDocumentation  is unaware of the completed authentication process.
and finally, getParameters -> fetchResource makes a call with the missing authentication  header.

These three calls are related to ListGuesser, schemaAnalyzer...

`resource.getParameters	@	2.chunk.js:3870
resolveSchemaParameters	@	2.chunk.js:2416
getOrderParametersFromSchema	@	2.chunk.js:2443

resource.getParameters	@	2.chunk.js:3870
resolveSchemaParameters	@	2.chunk.js:2416
getFiltersParametersFromSchema	@	2.chunk.js:2456

resource.getParameters	@	2.chunk.js:3870
resolveSchemaParameters	@	2.chunk.js:2416
getFiltersParametersFromSchema	@	2.chunk.js:2456`

@alanpoulain  can you help with this issue?

**Comment by benfavre** [comment]
This makes the whole platform completely unsuable ..
Not sure what the deal is but it seems like an issue with fetch, as the token is correctly set right before the call to fetch in fetchJsonLd.js

**Comment by benfavre** [comment]
Found it !
The issue is in api-doc-parser.
The doc parse doesn't have an argument to supply a custom HttpClient and so it uses the api-platform/admin "fetchJsonLd" method no matter what.
Also here : https://github.com/api-platform/api-doc-parser/blob/bdba5a17f8428a48df64dc63f723c5818a6da92c/src/hydra/fetchResource.ts#L10
There is a Object.assign() call used instead of what could be object destructuring. Hence we are passing a copy of a reference to the options parameters instead of creating a new object each time.
````
return fetchJsonLd(
    resourceUrl,
    { itemsPerPage: 0 , ...options}
  )
```

**Comment by benfavre** [comment]
https://github.com/api-platform/api-doc-parser/pull/88

**Comment by benfavre** [comment]
As it stands the only way to fix this without my PR and a closure for the Header is to do something like this in security.yaml

```yaml
firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        api_public_routes:
            pattern: ^/api/(docs|docs.jsonld|contexts/Entrypoint)
            stateless: true
            anonymous: true
        
        api:
            pattern: ^/api/
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

**Comment by alanpoulain** [comment]
Could you try to make this change: https://github.com/api-platform/docs/pull/1184

It should fix your issue.

**Comment by artemkozlenkov** [comment]
Hello everybody, wanted to try api-platform-admin with api-platform backend, followed simple instruction to create react project and point to my backend api like so 
```import logo from './logo.svg';
import './App.css';
import { HydraAdmin } from "@api-platform/admin";

function App() {
  return (
      <HydraAdmin entrypoint="http://127.0.0.1:8000" />
  );
}

export default App;
```
the very first time it works, but when i move it to other host location or dockerize it I also get 
```Unhandled Rejection (Error): Unreachable resource
./node_modules/@api-platform/api-doc-parser/lib/hydra/fetchResource.js/exports.default/<
src/hydra/fetchResource.ts:16

  13 | });
  14 | //# sourceMappingURL=fetchResource.js.map
```
it it a bug? 
thanks in advance.

**Comment by artemkozlenkov** [comment]
> Hello everybody, wanted to try api-platform-admin with api-platform backend, followed simple instruction to create react project and point to my backend api like so
> 
> ```
> import './App.css';
> import { HydraAdmin } from "@api-platform/admin";
> 
> function App() {
>   return (
>       <HydraAdmin entrypoint="http://127.0.0.1:8000" />
>   );
> }
> 
> export default App;
> ```
> 
> the very first time it works, but when i move it to other host location or dockerize it I also get
> 
> ```
> ./node_modules/@api-platform/api-doc-parser/lib/hydra/fetchResource.js/exports.default/<
> src/hydra/fetchResource.ts:16
> 
>   13 | });
>   14 | //# sourceMappingURL=fetchResource.js.map
> ```
> 
> it it a bug?
> thanks in advance.

sorry, not a bug for me, make sure you have database pre-populated, works!
worth mentioning the 'api-platform admin' is an adapter for 'react-admin' framework though looking at both may benefit

**Comment by alanpoulain** [comment]
Should be solved with https://github.com/api-platform/docs/pull/1228.
Feel free to reopen if not.
