### ISSUE TITLE
Error after enabling Partial Pagination

### ISSUE THREAD

**Issue by freakheart** [api-platform/admin#276]
I have a table with 7 million rows, so pagination is very slow since it is running the count query. So I have set the partial pagination to true in my Global configuration.

But in the admin section when I select this table I am getting the below error.

Given action "RA/CRUD_GET_LIST_SUCCESS", reducer "total" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

Any one has any idea, any help will be much appreciated. Thanks.

Edit 1: More info and Steps to Reproduce added.

1. A normal request would return a Response with "totalItems"
`"hydra:totalItems": 3328`
2. When you enable Partial Pagination then we don't have "totalItems" in the Response anymore. I Think this is a problem in the admin since it is always expecting "totalItems".

**Steps to Reproduce:**
1. Enable Partial Pagination
`# api/config/packages/api_platform.yaml
api_platform:
    collection:
        pagination:
            partial: true # Disabled by default`
2. Browse the admin and you will get the error.

**Comment by freakheart** [comment]
any one?

**Comment by freakheart** [comment]
Well, if I add this `if (!isset($data['hydra:totalItems'])) {
            $data['hydra:totalItems'] = 1000;
        }` 
to '/api-platform/core/src/Hydra/Serializer/PartialCollectionViewNormalizer.php::normalize' then it is working.

**Comment by yskolnick** [comment]
Having the same issue...

**Comment by soyuka** [comment]
really not sure what's going on here, please provide more informations about how to reproduce and if the issue arise with a simple http request so that I know if it's an issue in the admin or not.

**Comment by freakheart** [comment]
More info and Steps to Reproduce added.

**Comment by soyuka** [comment]
thanks I understand better, I'm not sure how react-admin should be configured to handle partial pagination.

**Comment by VivianDoreen** [comment]
Having the same issue...

**Comment by soyuka** [comment]
could you try my patch?

**Comment by VivianDoreen** [comment]
ok, thanks

**Comment by emulienfou** [comment]
For information, same issue happens when you disabling pagination for an entity, such as:
`@ApiResource(attributes={"pagination_enabled"=false})`

**Comment by ssengedonazil** [comment]
I have same ussue
