### ISSUE TITLE
Invalid itemUrl after upgrade to v2.0.0

### ISSUE THREAD

**Issue by oleg-andreyev** [api-platform/admin#286]
**API Platform version(s) affected**: 2.1.0

**Description**  
Performing any item-operation getting invalid `itemUrl` in `convertReactAdminRequestToHydraRequest`

**How to reproduce**  
- Perform any item operation e.g.: DELETE

**Possible Solution**  
`itemUrl` should be built same way as `collectionUrl`

**Additional Context**  
![image](https://user-images.githubusercontent.com/1244112/78295341-a712d580-7534-11ea-83e7-44c659262c43.png)

*Actual result*
`https://127.0.0.1:8000/api/<uuid>`

*Expected result*
`https://127.0.0.1:8000/api/<resource>/<uuid>`

**Comment by andrekutianski** [comment]
Same problem here. You get a solution for this @oleg-andreyev ?
