### ISSUE TITLE
ReferenceField ignores custom headers in request

### ISSUE THREAD

**Issue by DenisVorobyov** [api-platform/admin#293]
v2.1.0, v2.1.1

**Description**  
I have custom auth header like described in https://marmelab.com/react-admin/DataProviders.html

in 2.0.1 works well

**How to reproduce**  
Add ReferenceField to i.e. List

**Comment by alanpoulain** [comment]
You can add custom headers by modifying the `fetchHydra` parameter of the `hydraDataProvider`.
