### ISSUE TITLE
useGetOne() hook forgets about the resource

### ISSUE THREAD

**Issue by ackalhan** [api-platform/admin#296]
```
import { useGetOne } from 'react-admin';

const UserProfile = () => {
    const userId = 10;
    const { data, loaded, error } = useGetOne('users', userId);

    if (!loaded) return "NOT LOADED...";
    if (error) return "ERROR";
    if (!data) return "NO DATA";

    return (
        <ul>
            <li>Name: {data.name}</li>
            <li>Email: {data.email}</li>
        </ul>
    )
}
```

in this **useGetOne** i'am expecting a request like **`users/10`**
instead it will pointed to **`/10`**

When i see this line https://github.com/api-platform/admin/blob/ba0630083f28eaa8806bc1da4613677924604a52/src/hydra/dataProvider.js#L282
it's pointed to **`itemUrl`** which is evaluates to `https://localhost:8443/10` in my case

- entrypoint is `https://localhost:8443`
- window.location.href is `https://localhost:444/#/`
```
const entrypointUrl = new URL(entrypoint, window.location.href);
const itemUrl = new URL(params.id/*10*/, entrypointUrl);
```
- This look like when creating itemUrl we forget about the resource

May be i could miss something

**Comment by alanpoulain** [comment]
It's because the admin (and the hydra data provider) is using IRIs, not IDs. In your case `userId` (`userIri`) should be `/users/10`.
