### ISSUE TITLE
Issues with useEmbedded = true

### ISSUE THREAD

**Issue by seltzlab** [api-platform/admin#300]
**API Platform version(s) affected**: 2.2.0

**Description**  
When using the `useEmbedded = true` parameter with the `HydraDataProvider` fetching a nested resource is failing because the built URL is not valid (trying GET /[object%20Object])

**How to reproduce**  
I have this .jsonld produced by my Api-platform APIs.
There's a resource Publisher (https://gist.github.com/seltzlab/dd9651b28b81ec35527cf01d060781bf#file-jsonld-L1291) that embeds a MediaType resource https://gist.github.com/seltzlab/dd9651b28b81ec35527cf01d060781bf#file-jsonld-L977

In he Publisher list view everything is fine, I can print the MediaType.name property without any issue

```
const PublishersList = props => (
    <List {...props} exporter={false}>
        <Datagrid>
            <FieldGuesser source="name" />
            <TextField source="type.name" label="Media type" sortable={false} />
            <FieldGuesser source="country_code" sortable={false} />
            <EditButton />
        </Datagrid>
    </List>
);
```

But within the edit view the Autocomplete gets no value and I see the provider trying to retrieve GET /[object%20Object]

```
export default function PublisherEdit(props) {
    return <Edit {...props} actions={<React.Fragment />}>
        <SimpleForm variant="outlined">
            <Typography variant="h5">Edit publisher</Typography>
            <TextInput source="name" fullWidth />
            <ReferenceInput label="Media type" reference="media-types" source="type">
                <AutocompleteInput optionValue="id" optionText="name" options={{variant: "outlined"}} fullWidth pagination={false}/>
            </ReferenceInput>
            <TextInput source="country_code" label="Country code (2 chars)" />
        </SimpleForm>
    </Edit>;
}
```

**Additional Context**  
Digging into the hydraDataProvider I've seen that into convertReactAdminRequestToHydraRequest the `params.id` is an object itself.
Without the useEmbedded the edit view looks working fine, while the list is not.

**Comment by alanpoulain** [comment]
Since it's an embedded field, you shouldn't use a `ReferenceInput` but the `AutocompleteInput` directly.

**Comment by seltzlab** [comment]
Thanks @alanpoulain for your reply!
I've tried with  `<AutocompleteInput source="type" options={{variant: "outlined"}}/>`, the network error doesn't happen anymore but the field is not populated (neither the list of values and the selected value)

**Comment by alanpoulain** [comment]
Shouldn't it be `<AutocompleteInput source="type.name" options={{variant: "outlined"}}/>`?

**Comment by seltzlab** [comment]
Unfortunately not, I've also tried with `<AutocompleteInput source="type" optionValue="type.id" optionText="type.name" options={{variant: "outlined"}}/>` but it's not working

**Comment by seltzlab** [comment]
Looking at the network flow I see that if `AutocompleteInput` is decorated with `ReferenceInput` a couple of `GET /api/media-types` are dispatched (one with url query, one without), plus once the `GET /[object%20Object]`

![Selection_069](https://user-images.githubusercontent.com/818707/83008088-e9c4cb80-a014-11ea-9ddf-c36f588d1f53.png)

While if I only put the `AutocompleteInput` none of the network calls to media-types is dispatched.

**Comment by alanpoulain** [comment]
Seems normal, see its documentation: https://marmelab.com/react-admin/Inputs.html#referenceinput.

**Comment by seltzlab** [comment]
Yes it's normal that ReferenceInput tries to fetch the list and the value probably.
The bug is with the data provider probably. Not sure what's the right way to solve this issue, I'm pretty sure the use case is quite normal, so maybe I'm doing something wrong?

**Comment by alanpoulain** [comment]
I've added a documentation here: https://github.com/api-platform/docs/pull/1116.

Basically you need to add:
```js
format={v => v['@id'] ?? v}
```
to your `ReferenceInput`.

**Comment by seltzlab** [comment]
@alanpoulain great thanks, it works.
I had to change the format function with

```
 format={v => typeof v === 'object' && v.hasOwnProperty('@id') ? v['@id'] : v}
```

because if v is null it fails with `Cannot read property '@id' of null`
