### ISSUE TITLE
Introspecter dataprovider call

### ISSUE THREAD

**Issue by L-Luciano** [api-platform/admin#304]
**API Platform version(s) affected**: 
api platform 2.1.1
react admin 3.6

**Description**  
Introspecter send an error : 
Uncaught Error: Unknown dataProvider function: introspect

**Comment by alanpoulain** [comment]
Please give more context to this issue.

**Comment by L-Luciano** [comment]
When I update react-admin to 3.6. 
The ResourceIntrospecter failed on the useDataProvider.introspect().
It's like dataprovider was typed without introspect method.

**Comment by alanpoulain** [comment]
Updated the demo to 3.6, doesn't have this issue.

**Comment by L-Luciano** [comment]
Hi,
My error log :

useDataProvider.js:166 Uncaught Error: Unknown dataProvider function: introspect
    at Proxy.<anonymous> (useDataProvider.js:166)
    at Introspecter.js:189

The above error occurred in the <Introspecter> component:
    in Introspecter (at ListGuesser.js:240)
    in ListGuesser (created by WithPermissions)
    in WithPermissions (created by Context.Consumer)
    in Route (created by ResourceRoutes)
    in Switch (created by ResourceRoutes)
    in ResourceRoutes (created by Resource)
    in Resource (created by ResourceGuesser)
    in ResourceGuesser (at SaceAdmin.js:45)

**Comment by alanpoulain** [comment]
Are you using the right data provider? From the `hydra` folder?

**Comment by L-Luciano** [comment]
I have a data provider based on it but I customize it because I need to merge 2 entrypoints.

Introspect method : 

`
introspect: () =>

            apiSchema
                ? Promise.resolve({ data: apiSchema })
                : Promise.all(entrypoints.map(apiDocumentationParser))
                      .then((fetchedApis) => {
                          const customRoutes = fetchedApis
                              .map((fetchedApi) => fetchedApi.customRoutes)
                              .shift();
                          apis = [
                              ...fetchedApis.map(
                                  (fetchedApi) => fetchedApi.api
                              ),
                          ];

                          apiSchema = {
                              resources: apis
                                  .map((api) => api.resources)
                                  .flat(),
                          };
                          return { data: apiSchema, customRoutes };
                      })
                      .then(({ data, customRoutes = [] }) => {
                          if (
                              0 === customRoutes.length &&
                              data.resources.find(
                                  (resource) => 'translations' === resource.name
                              )
                          ) {
                              fetchApi(GET_LIST, 'translations', {
                                  pagination: { page: 1 },
                                  sort: {},
                              }).then(manageTranslations);
                          }
                          return { data, customRoutes };
                      })
                      .catch(({ error, status }) => {
                          throw new Error(
                              'Cannot fetch API documentation:\n' +
                                  (error
                                      ? `${error.message}\nHave you verified that CORS is correctly configured in your API?\n`
                                      : '') +
                                  (status ? `Status: ${status}` : '')
                          );
                      })
`

**Comment by alanpoulain** [comment]
I'm not sure why but I think it's because of your custom data provider then.

**Comment by L-Luciano** [comment]
ok thanks. 

I found my pb. I fork the admin guesser to customize my list/create/edit/show props of AdminResourcesGuesser (I dit it dynamically from the api context).
I used the SchemaAnalyzerContext and Introspecter from @api-platform/admin and I suppose it's impossible. I forked them too and it's good.
