### ISSUE TITLE
Show and edit use incorrect api endpoint

### ISSUE THREAD

**Issue by wim-beck** [api-platform/admin#305]
**API Platform version(s) affected**: 2.1.1

**Description**  
Going to the show or edit page of an entry does not use the correct API endpoint. Saving an entry uses the same URL and has therefore the same incorrect behavior.

**How to reproduce**  
Core application is hosted at localhost
API is hosted at localhost/api
Admin is hosted at localhost/admin

Entity type example is "members". The list view displays correctly and fetches data from localhost/api/members. Show and edit view should fetch data from localhost/api/members/id, but these calls go to localhost/id instead.

Entrypoint for HydraAdmin is configured to be localhost/api.

**Possible Solution**  
Change buildup of the itemURL in the hydraDataProvider. I was able to fix the issue locally. I am now working on a pull request.

**Comment by alanpoulain** [comment]
API Platform Admin is using IRIs, not IDs.
