### ISSUE TITLE
Minor: Wrong translation key when loading content

### ISSUE THREAD

**Issue by loeyan** [api-platform/admin#315]
Hi,

during development I found a small translation key issue. The Key "ra.page.loading" is used, but this key does not exist.
It should be "ra.message.loading"

![image](https://user-images.githubusercontent.com/8937313/88351971-78757080-cd58-11ea-9d6f-a8eb289e0857.png)

I just updated to ra-language-english@3.7.1 and here it is another key
![image](https://user-images.githubusercontent.com/8937313/88352056-b2467700-cd58-11ea-9998-7c7a44177d3b.png)

BR
Yannick

P.S.: Thanks for your great work!

**Comment by dunglas** [comment]
Hi, thanks for reporting! Would you mind ton open a Pull Request?

**Comment by loeyan** [comment]
Hi,
this issue can be closed. The maintainer of the german language did not push his changes properly (still in version 2.x.y and should be 3.x.y)... 
Also see https://github.com/greenbananaCH/ra-language-german/pull/16
