### ISSUE TITLE
Error message is lost after 2.2.1 release

### ISSUE THREAD

**Issue by oleg-andreyev** [api-platform/admin#316]
**API Platform version(s) affected**: 2.2.1 

**Description**  
When executing `apiDocumentationParser` before 2.2.1, I would get error message with explanation why exactly is wrong. 

**How to reproduce**  
`apiDocumentationParser` should throw an Error

**Error 2.2.1**
```
Error: Cannot fetch API documentation:
Have you verified that CORS is correctly configured in your API?
```

**Before 2.2.1**
```
Error: Cannot fetch API documentation:
Unable to find the URL for "https://127.0.0.1:8000/api/docs.jsonld#Entrypoint/transaction", make sure your api resource has at least one GET item operation declared.
Have you verified that CORS is correctly configured in your API?
```

**Comment by soyuka** [comment]
#318 fixes this

**Comment by soyuka** [comment]
tagged in v2.2.2 please let me know if the issue arise
