### ISSUE TITLE
The empty state is not displayed in the list page when there are no records for a resource

### ISSUE THREAD

**Issue by Luwangel** [api-platform/admin#320]
**API Platform version(s) affected**: 2.5.6

**Description**

I'm running the demo project provided by API-Platform following your tutorial: https://api-platform.com/docs/distribution/#installing-the-framework.

The first time I open the admin, there are no greetings but instead of seeing the React-Admin empty state, I see the following empty list:

![Not Empty State](https://user-images.githubusercontent.com/5584839/90232108-75801400-de1c-11ea-919c-a0b98cc05d68.png)

The expected result is:

![Empty State](https://user-images.githubusercontent.com/5584839/90232326-cc85e900-de1c-11ea-9b6e-b941cca836ce.png)

**How to reproduce**  

- Download API-Platform `v2.5.6`
- Run `docker-compose pull` and then `docker-compose up -d`
- Open the admin: `https://localhost:444`
=> An empty list is displayed instead of having the React-Admin empty state

**Possible Solution**  

As I wrote in my first screenshot, the total of elements passed to the list is `-1`. But in React-Admin, we only test `!total`.

``` js
// In React-Admin
// File packages/ra-ui-materialui/src/list/ListView.tsx
const shouldRenderEmptyPage =
    hasCreate &&
    loaded &&
    !loading &&
    !total && // Here is the issue
    !Object.keys(filterValues).length;
```

Find the `<ListView>` here: https://github.com/marmelab/react-admin/blob/af879fb92783ea8c12d99d86088bcfdf165dabcf/packages/ra-ui-materialui/src/list/ListView.tsx#L90

We cannot change React-Admin by testing for example `total <= 0` because you seem to use other values like `-2` or `-3`.
 
So I think the solution is to change the hydra data provider to return 0 instead of -1 and find another way to deal with "next page" and "no information". 

Find the hydra data provider here: https://github.com/api-platform/admin/blob/b555ce6d2c9cdc68d4f46e00934ffbcdcf60a9ed/src/hydra/dataProvider.js#L378

If you have any question, please ask me.

Have a good day,
Adrien

**Comment by alanpoulain** [comment]
It was not working because `0` is a falsy value. I've made a fix and I'll release a patch version.
