### ISSUE TITLE
[QUESTION] Use only as DataProvider

### ISSUE THREAD

**Issue by nckenn** [api-platform/admin#354]
Just want to ask, is it possible to use only the data provider, i want only to use the data provider of this library and pass the dataprovider to ``<Admin>`` instead of using the ``<HydraAdmin>``

**Comment by alanpoulain** [comment]
Hello. Yes it is.

**Comment by nckenn** [comment]
Using this code gives me error : Cannot read property 'resources' of undefined

```
    <Admin
      dataProvider={dataProvider}
      authProvider={authProvider}
      dashboard={Dashboard}
      layout={Layout}>
      
      <Resource name="billing-headers" {...billings}/>
    </Admin>
```

**Comment by neholouis** [comment]
Hello there. 

I have the same error as @nckenn ! Can't figure why it happens randomly.

Thanks ! :)
