### ISSUE TITLE
Provide documentation on how to use multiple dataproviders

### ISSUE THREAD

**Issue by freakheart** [api-platform/admin#368]
**Description**  
Please provide some documentation on how I can have more than one data provider using API platform admin.

**Example**  
I have 3 APIs and I want to build one Admin app that can use all those APIs. React-admin has a way to do this, but I am not sure how to do it using API platform admin. Any info would be great. Thanks.

**Comment by alanpoulain** [comment]
I don't think the documentation should be here.
The `AdminGuesser` component is using the same `props` as the `Admin` component in react-admin.
You can do exactly the same in react-admin and in API Platform admin.

**Comment by freakheart** [comment]
What about the possibility to have more than one Entrypoint?

**Comment by alanpoulain** [comment]
You should create your own data provider to do that.
