### ISSUE TITLE
Using a pathas entrypoint crashes

### ISSUE THREAD

**Issue by dunglas** [api-platform/admin#372]
This crashes `<HydraAdmin entrypoint="/" />` while this works `<HydraAdmin entrypoint={window.origin} />`. It would be nice to support for non-absolute URLs, especially now that the distribution exposes the API and the PWA on the same domain.

Relate to https://github.com/api-platform/api-platform/pull/1850

**Comment by afilp** [comment]
Hello, interested on that too, is it still an issue? Thanks.
