### ISSUE TITLE
<ReferenceInput> with EditGuesser  not filled or failed to save

### ISSUE THREAD

**Issue by cedriclombardot** [api-platform/admin#373]
**API Platform version(s) affected**: "@api-platform/admin": "^2.6.0" and "api-platform/core": "^2.6"

**Description**  

Hi,

We are using ApiPlatform with react-admin and we got a problem,
Got this entity and the related on VehicleType

```
class Formula
{
    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private $id;
    ....
    /**
     * @ORM\ManyToOne(targetEntity=VehicleType::class, inversedBy="formulas")
     * @ORM\JoinColumn(nullable=false)
     */
    #[Groups([ "read_formula", "write_formula"])]
    private $vehicleType;
    ...
}

```
On the react side useEmbedded is enabled :

```
const dataProvider = baseHydraDataProvider(
  entrypoint,
  fetchHydra,
  apiDocumentationParser,
  true // useEmbedded parameter
);

```

But when i m on FormulaEdit :

```
const FormulaEdit = (props) => {
  return (
    <EditGuesser {...props}>
      <InputGuesser source="name" />
      <ReferenceInput source="vehicleType" reference="vehicle_types">
        <SelectInput optionText="label" />
      </ReferenceInput>
    </EditGuesser>
  );
};

```
I got the select but not selected with my db value
If i select one value, it well saved.
If i use

```
<ReferenceInput source="vehicleType.@id" reference="vehicle_types">
    <SelectInput optionText="label" />
</ReferenceInput>
```

The field is filled, but on save i got the error :

`hydra:description: "Nested documents for attribute "vehicleType" are not allowed. Use IRIs instead."`

What is the good method to deal with relation, in documentation we only found the first method but field is not filled :'(

**Comment by alanpoulain** [comment]
Is this PR helping you? https://github.com/api-platform/docs/pull/1144

**Comment by cedriclombardot** [comment]
@alanpoulain Thanks a lot !!!!!!
