### ISSUE TITLE
New Project Setup Currently Failing

### ISSUE THREAD

**Issue by jspizziri** [api-platform/admin#377]
**API Platform version(s) affected**: 2.6.0

**Description**  
Following the "[Getting Started](https://api-platform.com/docs/admin/getting-started/)" documentation fails on install of `@api-platform/admin` due to a version conflict with `react` in the `final-form-submit-errors@"^0.1.0"` dependency.

**How to reproduce**  
```
npx create-react-app my-app --template typescript
cd my-app
npm i @api-platform/admin
```

**Possible Solution**  

It seems that the `final-form-submit-errors` package has [a peerDependency on `react@^16.8.6`](https://github.com/ignatevdev/final-form-submit-errors/blob/master/package.json#L71). 

I'm guessing the best solution is to get the aforementioned package upgraded. However, if that's not the best approach I think the react dep will need to be backed off to 16.

Incidentally as a temporary solution for people it should be possible to downgrade your react app dependencies:

```
npm i react@^16.9.0 react-dom@^16.9.0 @types/react@^16.9.0 @types/react-dom@^16.9.0
```

**Additional Context**  

Corresponding [Issue in `final-form-submit-errors`](https://github.com/ignatevdev/final-form-submit-errors/issues/7).

Error message:

```
❯ npm i @api-platform/admin
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@11.2.6
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.2.6" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @testing-library/react@11.2.6
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^11.2.6" from the root project
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     1 more (@api-platform/admin)
npm ERR!   3 more (react-scripts, the root project, @api-platform/admin)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from final-form-submit-errors@0.1.2
npm ERR! node_modules/@api-platform/admin/node_modules/final-form-submit-errors
npm ERR!   final-form-submit-errors@"^0.1.0" from @api-platform/admin@2.6.0
npm ERR!   node_modules/@api-platform/admin
npm ERR!     @api-platform/admin@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by jspizziri** [comment]
Update:

The `final-form-submit-errors` has released a patch version that fixes this issue form NPM installs. I believe all that remains is for this project to update the `yarn.lock` (I'm an npm user).

**Comment by alanpoulain** [comment]
The `yarn.lock` file is only useful for the development. I think this issue can be closed. Thanks.
