### ISSUE TITLE
Can't customize List and Show views independently

### ISSUE THREAD

**Issue by avinesse** [api-platform/admin#38]
Hello,

I am using custom components to display readableFields in the 'Show' view for my Resource. 
However, I don't want these fields to appear in the 'List' view but I haven't found a way to customize these views separately. 

Do you confirm that this is not possible as of now, or did I miss the way to do it ?

Thank you.
Anouk

**Comment by dunglas** [comment]
IIRC @mauchede has been working on a patch to make this easy. In the meantime it still possible to override the AOR config to have a different one for list and show.

**Comment by mauchede** [comment]
Indeed, I worked on this problem. I will try to push soon the modifications.

**Comment by avinesse** [comment]
Closing, since the solution seems to work perfectly. Thanks @mauchede :)
