### ISSUE TITLE
history v5.0.0 not working with react-admin

### ISSUE THREAD

**Issue by gartner** [api-platform/admin#382]
**API Platform version(s) affected**: 2.6.1

**Description**  
After an upgrade to api-platform/admin v. 2.6.1, the react-admin frontend cannot switch between resources. An 'Uncaught Could not find router reducer in state tree, it must be mounted under "router"' is thrown.

Accoring to this: https://marmelab.com/react-admin/Admin.html#history, react-admin will not work with history v.5.0.0.
The admin has that version as a dependency from v. 2.6.1

**Possible Solution**  
The dependency on history should be downgraded to ^4.10.1 again

**Comment by alanpoulain** [comment]
Should be fixed in 2.6.2, sorry!
