### ISSUE TITLE
Admin component - getPolyfill is not a function

### ISSUE THREAD

**Issue by unsigned-studio** [api-platform/admin#391]
**API Platform version(s) affected**: 2.6
"@api-platform/admin": "^2.6.4"

**Description**  
A created my API on Api Platform Symfony backend - everything is working perfect - thanks for your hard work on ApiPlatform!

My next step is to create easy admin panel to manage and moderate some records. 

When I am going throught the documentation steps:
- yarn create react-app my-admin
- yarn add @api-platform/admin
- I have also found about: yarn add isomorphic-fetch (as I am working on docker node container)
- yarn start
my admin app is reporting error:

> TypeError: getPolyfill is not a function
> ./node_modules/array.prototype.foreach/index.js
> node_modules/array.prototype.foreach/index.js:10
>    7 | 
>    8 | var implementation = require('./implementation');
>    9 | var getPolyfill = require('./polyfill');
> > 10 | var polyfill = getPolyfill();
>   11 | var shim = require('./shim');
>   12 | 
>   13 | var $slice = callBound('Array.prototype.slice');

I am working with admin app on Docker Container based on node:lts-alpine, but when I was on 12.2 result was the same.

Any ideas/suggestions?

**How to reproduce**  
Just go through the Documentation steps of Admin component:  https://api-platform.com/docs/admin/getting-started/

**Comment by alanpoulain** [comment]
Hello,
Sorry it doesn't seem to be an issue in our code. You should dig deeper to understand what is going on.
