### ISSUE TITLE
no calendar on date or datetime fields on firefox

### ISSUE THREAD

**Issue by fecou** [api-platform/admin#393]
I just installed api-platform (with symfony core, not distribution). 
I also installed independently the admin with yarn add @api-platform/admin
The admin works well and recognizes my entities correctly. But with date and datetime fields, textfield is blocked and so there is no way to create an entity when date (or datetime) field is not nullable.
I tried with this (see  : https://api-platform.com/docs/admin/customizing/#customizing-the-create-form )
const ProjectsCreate = props => (
    <CreateGuesser {...props}>
    <DateTimeInput source="publicationDate" />
    <InputGuesser source="testDate" />
    </CreateGuesser>
);
But it still doesn't work.
In my console, I have an error : Material-UI: the createMuiTheme function was renamed to createTheme.
Any idea how to correct this ?

**Comment by fecou** [comment]
I just realized that it works correctly on Chromium, but it doesn't works with firefox (78.13.0esr (64-bit) on linux debian distrib).
I made tests with the api-platform distribution and the result is the same (works on Chromium but not on firefox).

**Comment by dunglas** [comment]
Thanks for investigating! Shouldn't this bug be reported upstream (probably to react admin)? I doubt (but I've not checked) that the bug is directly in our code.

**Comment by fecou** [comment]
I looked for such issues in react-admin on github. Maybe the problem with firefox could be related with this issue : https://github.com/marmelab/react-admin/issues/5324#issuecomment-701344690

**Comment by cpetit-sigma-fr** [comment]
Seems it will be implemented in Firefox 93 on 2021-10-05, cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/datetime-local#browser_compatibility
I didn't know that the Mozilla Foundation marked unreleased things as compatible, and it won't be in any ESR version soon...
