### ISSUE TITLE
Control client-side URLs

### ISSUE THREAD

**Issue by Jayfrown** [api-platform/admin#398]
I'm choosing to open this support question on GitHub, disregarding the mentions of "community support" on StackOverflow and Symfony Slack. The reason for this is neither channels yield any answers to my questions. I've also tried on the unofficial discord for React-Admin, to no avail.

In short, my issue is as follows:

- My backend uses API Platform, all my entities use Uuidv6 identifiers
- My frontend uses `@api-platform/admin`'s `<HydraAdmin>` react-admin component
- All URLs on my frontend look like such:

```
http://localhost:3000/#/customers/%2Fapi%2Fcustomers%2F1ebf9fba-af5a-6d7e-aaef-c714187cd97e/show
```

This is because the API Platform backend returns IRIs like `/api/<resource>/<Uuidv6>` instead of just returning the uuid, and the `@api-platform/admin` builds urls like `/<resource>/<IRI>/[show|edit]`.

There are two ways to approach this:

1. Handle this client side, probably in the dataProvider?
2. Make backend return uuid instead of "full path" IRI

Handling this on the client-side seems preferable, but pointers on either side would be greatly appreciated.

**Comment by alanpoulain** [comment]
Hello,
We don't plan to support anything else than IRI for the identifiers, sorry.

**Comment by Jayfrown** [comment]
So this URL structure is expected, even when not using UUIDs?

For example:

```shell
"Customer 1234": http://localhost:3000/#/customers/%2Fapi%2Fcustomers%2F1234/show
"Customer 1ebf9fba-af5a-6d7e-aaef-c714187cd97e": http://localhost:3000/#/customers/%2Fapi%2Fcustomers%2F1ebf9fba-af5a-6d7e-aaef-c714187cd97e/show
```

There's nothing I can do in the dataProvider to translate between UUID and IRI?

**Comment by alanpoulain** [comment]
Yes it is expected. You could try to use your own data provider, but I'm not sure it is worth it.

**Comment by Jayfrown** [comment]
Thanks. I really felt a need for this so I ended up making a local copy of the upstream `src/hydra/dataProvider.js` with some changes.

If anyone's interested, here's the diff. I might have inadvertently broken something by doing this, ymmv.

```diff
diff --git a/src/Providers/hydraDataProvider.js b/src/Providers/hydraDataProvider.js
index fa16e86..98912bd 100644
--- a/src/Providers/hydraDataProvider.js
+++ b/src/Providers/hydraDataProvider.js
@@ -1,3 +1,4 @@
+/* eslint-disable import/no-anonymous-default-export */
 import {
   CREATE,
   DELETE,
@@ -8,14 +9,16 @@ import {
 } from 'react-admin';
 import isPlainObject from 'lodash.isplainobject';
 import { parseHydraDocumentation } from '@api-platform/api-doc-parser';
-import fetchHydra from './fetchHydra';
-import { resolveSchemaParameters } from './schemaAnalyzer';
+import { fetchHydra } from '@api-platform/admin';
+import { resolveSchemaParameters } from '@api-platform/admin/src/hydra/schemaAnalyzer';
 
 class ReactAdminDocument {
   constructor(obj) {
+    const iriParts = obj['@id'].split('/');
+    const uuid = iriParts[iriParts.length - 1];
     Object.assign(this, obj, {
       originId: obj.id,
-      id: obj['@id'],
+      id: uuid,
     });
   }
 
@@ -232,7 +235,16 @@ export default (
   const convertReactAdminRequestToHydraRequest = (type, resource, params) => {
     const entrypointUrl = new URL(entrypoint, window.location.href);
     const collectionUrl = new URL(`${entrypoint}/${resource}`, entrypointUrl);
-    const itemUrl = new URL(params.id, entrypointUrl);
+    let url;
+
+    // Relationships still have full IRIs
+    if (params.id && params.id.includes("/")) {
+      url = params.id;
+    } else {
+      url = `${entrypoint}/${resource}/${params.id}`;
+    }
+
+    const itemUrl = new URL(url, entrypointUrl);
     const searchParams = params.searchParams || {};
     for (const searchParamKey in searchParams) {
       if (!searchParams.hasOwnProperty(searchParamKey)) {
```
