### ISSUE TITLE
React and Admin On Rest support

### ISSUE THREAD

**Issue by dunglas** [api-platform/admin#4]
See https://github.com/dunglas/admin/tree/react

TODO:

* [x] Create a Hydra parser
* [x] Create an intermediate representation for the API client
* [x] Create a Hydra client
* [x] Add a bridge with Admin On Rest
* [x] Add pagination support
* [x] Allow to decorate the Field and Input factory
* [x] Add support filters
* [x] Extract the Hydra parser in a separate repository
* [x] Add tests
* [x] Add a generator for Redux Form (react and react native)

ping @meyerbaptiste

**Comment by wadjeroudi** [comment]
@dunglas when you say "add support filters", you mean to create dynamic dropdown filters with values depending on the whole result set ? How do you imagine to do that ?
A request for each list or each filter ?

**Comment by rande** [comment]
@dunglas I just quickly check the code, sorry if I get it wrong, but the admin project doesn't seems to handle server side validation with error related on each field. It is the only place where you catch error: https://github.com/api-platform/admin/blob/378a036ba899c82f41af0c3bc633fb62260018c4/src/hydra/fetchHydra.js#L35-L43 and there is nothing about specific fields.

**Comment by dunglas** [comment]
@rande you're right, per field client-side validation is supported but server-side validation errors are always displayed as global errors for now.
We need to be careful when implementing per field server-side errors because Hydra doesn't support this (the list of field errors is a "proprietary" extension of API Platform).
The library may use this proprietary extension if available, but should fallback to the current implementation if not to preserve compatibility with the spec.

I'll work on this when I'll be back from vacation (but if someone wants to provide PR, he'/ very welcome 🙌).
