### ISSUE TITLE
License situation

### ISSUE THREAD

**Issue by Perni1984** [api-platform/admin#40]
Hello,

as we plan to use the api-platform admin in a project of ours, but I cannot find any licensing information here on github or in the sourcecode - could you kindly let us know under which license you are releasing api-platform-admin?

NPM is stating MIT: https://www.npmjs.com/package/api-platform-admin

Thanks

**Comment by dunglas** [comment]
It's indeed licensed under MIT. I'll add the file to the repository.

**Comment by Perni1984** [comment]
thanks
