### ISSUE TITLE
Hangs/Crashes/Unresponsiveness after a few sort and/or filtering actions

### ISSUE THREAD

**Issue by 4c0n** [api-platform/admin#413]
**API Platform version(s) affected**: 2.6.7

**Description**  
When using filters for filtering or sorting together with Mercure. After a few clicks things get really slow and/or unresponsive.
Eventually the eventsource type requests fail and allow for a new action, however the same thing happens quite soon after.
It also becomes impossible to refresh the page at this point. However closing a tab/window in the browser resets the problem.

**How to reproduce**  
Go to https://demo.api-platform.com/admin#/books and click the Author header about 7 times to sort the list by author.
You should see that the refresh button turns into the loading spinner. Now when you for example sort by a different column a few times it completely hangs and refreshing the page will no longer work.

**Comment by alanpoulain** [comment]
It seems it's because each time a sorting is done, all SSE streams are created again without closing the previous ones and it saturates the browser.
Something needs probably to be changed in https://github.com/api-platform/admin/blob/main/src/ListGuesser.js.

**Comment by 4c0n** [comment]
It seems that subsciptions are managed in the data provider and a reference to the dataprovider seems available from
https://github.com/api-platform/admin/blob/main/src/useMercureSubscription.js

I'd say it would probably be a good idea to fix the problem from there. Maybe you or @Shywim have a better idea?
There's no documentation on how this is supposed to work, so it's a little hard for me to understand, I'm also by no means an expert on any of this.

However the whole Mercure feature just makes the admin very unusable at this point and the only way to get around it is to just disable it. Which is a shame, because it would be really nice to have.
