### ISSUE TITLE
Authentication Example from Docs not Working

### ISSUE THREAD

**Issue by eloyekunle** [api-platform/admin#42]
Hello, Everyone.
I was following the [authentication example](https://github.com/api-platform/admin#add-authentication-support) from the README when I discovered that it wasn't working. I screamed **HAAAAAAA!!!**, then I determined to figure out what was wrong.
Hence, I discovered that
1. hydraClient had been updated, and the first parameter is now a JSON array of parameters. ([Before](https://github.com/api-platform/admin/blob/6bba7a6ba45b34af25b9720eb795639d04a425fa/src/hydra/hydraClient.js#L61); [After](https://github.com/api-platform/admin/blob/511c50bfd067d71aa4a01dce84de58cff5420b73/src/hydra/hydraClient.js#L68))
I think we can all agree that the documentation needs an update.

2. I made the correction in my code, then I got another error in my browser.
![screenshot from 2017-08-25 17-16-34](https://user-images.githubusercontent.com/11166933/29722553-374c7a30-89b9-11e7-9b76-5b47e3e93621.png)
I decided to figure out, again, what was happening. Well, I don't quite know how to describe this but the error disappeared after I changed this [line](https://github.com/api-platform/admin/blob/511c50bfd067d71aa4a01dce84de58cff5420b73/src/hydra/HydraAdmin.js#L38) from
`restClient={this.props.restClient(this.state.api)}`
to
`restClient={this.props.restClient}`

I gotta tell you, it's a bug. I probably wasn't clear enough here but if you got any more questions, I'll be glad to answer.
Great job, people.

PS: I'm not really a JS developer, you know.
PPS: I'm ready to get my hands dirty in this baby, just give me some pointers and I'll send in PRs.

**Comment by playmice** [comment]
Well, this won't be in the spirit of coolness, but my current workaround is to override the HydraAdmin, and add a prop called `httpClient`.
It has a default value called `fetchHydra`, but I'm overriding it by setting the `httpClient` prop to `fetchWithAuth`.

**Comment by sh41** [comment]
I've submitted a pull request at api-platform/docs#296 which you can see here:
https://github.com/sh41/docs/blob/9a51352e64c23f7a63178bbf59d8260ed7ee507a/admin/authentication-support.md

which I hope will help you to resolve this issue. Could you see if it helps?

**Comment by playmice** [comment]
Okay, I'll check it out.
Thanks for your help.
