### ISSUE TITLE
Admin Does Not Require authentication for docs.jsonld request

### ISSUE THREAD

**Issue by playmice** [api-platform/admin#43]
I noticed that when the whole symfony project is under a security layer, the Admin won't load because docs.jsonld returns 403 error. Normally, the 403 error should take you to the login page, but it doesn't in the case of docs.jsonld.
The only workaround for now is to open up docs.jsonld to anonymous users, which isn't good from a security perspective.

**Comment by dunglas** [comment]
Closed by #51.
