### ISSUE TITLE
Translations are not working as expected 

### ISSUE THREAD

**Issue by anjeylink** [api-platform/admin#432]
**API Platform version(s) affected**: 2.8.0

**Description**  
After upgrading to 2.8.0 part of translations stopped being translated. 
For example labels on loading page are translated, but labels in admin not. 

My guess is maybe it's because of `i18nProvider` prop is not passed down in `AdminGuesser` on `line 226`.

**Comment by alanpoulain** [comment]
Thank you again for the report.
You were perfectly right for the fix.
If you're willing to, don't hesitate to make a PR to fix it next time!
