### ISSUE TITLE
React admin 4 support

### ISSUE THREAD

**Issue by theMadness** [api-platform/admin#439]
I'm aware that react admin 4 is still in the beta stage, but due to its support of mui 5, it's something we likely need in our application, would it be possible to have a tagged version implementing it? Perhaps a 3.* dev?

**Comment by alanpoulain** [comment]
I'm working on it, see https://github.com/api-platform/admin/pull/438.

**Comment by theMadness** [comment]
Oh thank you for the prompt response Alan. Anything I can help with to get the PR merged sooner rather than later?

**Comment by alanpoulain** [comment]
It's mostly ready, I just need to test it and fix the remaining issues. I will ping you to test it if you want.

**Comment by theMadness** [comment]
If it's going to be helpful, absolutely.

**Comment by afilp** [comment]
@theMadness I am doing exactly the same, upgrading our `react-admin` app to v4 and actually need to release it very soon, even though it is in beta.2. If you want to exchange info on this, please ping me. Thanks.
