### ISSUE TITLE
ResourceGuesser does not display referenced data suggestions for ManyToOne relations

### ISSUE THREAD

**Issue by Gamesh** [api-platform/admin#442]
**Package versions**
- api-platform/core: v2.6.8
- api-platform/schema-generator: v4.0.1
- @api-platform/admin: v2.8.3

**Description**  
Can't get ManyToOne fields to work. All automatically rendered fields seems to have empty selections.
Tried manually overriding the CreateGuesser but it also does not display any suggestions. It just does not seems to render any suggestions even through the response returns data

**How to reproduce**  

Admin List
```javascript
<React.StrictMode>
    <HydraAdmin entrypoint="/api">
      <ResourceGuesser name="warehouse_parts" create={WarehouseParts} />
    </HydraAdmin>
  </React.StrictMode>
```

Warehouse part create guesser
```javascript
const WarehouseParts = (props: any) => (
  <CreateGuesser {...props}>
    <InputGuesser source="part"/>
  </CreateGuesser>
)
```
Full Response gist:
https://gist.github.com/Gamesh/17d91dd5bea51edc4377b4d2afb8e00e

Looks like this for other relations as well even if i don't change anything and only use ResourceGuesser with no customisations
![5rfwbqiu4N](https://user-images.githubusercontent.com/171747/163365327-ab1186b1-2ad2-4706-9a46-179d90c692a9.gif)

**Comment by Gamesh** [comment]
Ah it appears that if you don't expose a relation as a resource then you can't create relations or use that resource for autocomplete.
So the solution here was to add `<ResourceGuesser name="parts" />`

which kind of sucks as you can't selectively expose only a subset of resources. It's all or nothing, defeats the purpose of customizing

**Comment by gartner** [comment]
Instead of a ResourceGuesser, you can just add a
<Resource ...> imported from react-admin.
React-admin, used for the amin interface, requires a Resource to be present for things like related inputs to work. But a <Resource ..> that does not have an edit/create/list prop, will not display in the menu. See https://marmelab.com/react-admin/doc/3.19/Inputs.html#reference-inputs

**Comment by Gamesh** [comment]
Ah i see, good to know, thanks for the tip
