### ISSUE TITLE
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate.

### ISSUE THREAD

**Issue by tomekkowalczyk** [api-platform/admin#458]
**API Platform version(s) affected**: 2.6.8

**Description**  

The administration panel is displayed, while clicking the action causes an error in the console

BUG: Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

![image](https://user-images.githubusercontent.com/39382654/170457928-2581f6c4-35f0-48fe-88d3-868822998761.png)

package.json
![image](https://user-images.githubusercontent.com/39382654/170458099-e3ef28b9-1e90-48d9-bdcf-cd1aecc599a6.png)

 Yarn v1.17.3
 Node  v16.15.0

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by alanpoulain** [comment]
Hello,
Sorry there is not enough context to fix this. Could you create a reproducer?

**Comment by nickbass72** [comment]
Downgrading to React 17.0.2 resolves that issue for me.
