### ISSUE TITLE
displaying name of relation in place of iri does not work for https://schema.org

### ISSUE THREAD

**Issue by PawelSuwinski** [api-platform/admin#465]
**Description**  

When using `https://schema.org` displaying name in place of iri does not work, so this literal hint does not work (or any defaults generated from schema-generator):
https://api-platform.com/docs/admin/schema.org/#displaying-related-resources-name-instead-of-its-iri

only this one would:
```php
#[ApiProperty(iri: "http://schema.org/name")]
private $name;
```

Name hinting is hardcoded to `http://schema.org`:
https://github.com/api-platform/admin/blob/46b68715f1fd40e5916cd2e8d877808523b3b3b8/src/hydra/schemaAnalyzer.ts#L21

**Possible Solution**  
Match https also, i.e.
```js
  const field = schema.fields.find(
    (schemaField) => schemaField.id.match('https?://schema.org/name')
);
```

**Comment by papppeter** [comment]
Hi,

I couldn't get this feature to work.
i tried the original solution based on documentation. (iri does not exists in ApiProperty)
`
    #[ApiProperty(types: ["https://schema.org/name"])]
    private ?string $name = null;
`
i do see types if is run bin/console api:json-schema:generate 

![image](https://user-images.githubusercontent.com/3380880/218963306-1bd154de-73d7-442c-a3d3-5962a7832ade.png)

so how should i configure to see some name instend of IRI?

thanks for your help

**Comment by PawelSuwinski** [comment]
Try
```
#[ApiProperty(iris: ['https://schema.org/name'])]
```

**Comment by papppeter** [comment]
> #[ApiProperty(iris: ['https://schema.org/name'])]

Hi, it just works! thank you. i don't know how i did oversee this.

One more question, could you point to one of the documentation, if it is possible to have automaticaly autocomplet field in related field dropdowns on edit pages? 

![image](https://user-images.githubusercontent.com/3380880/219479081-87f2843f-a49c-4e56-9b9d-109e7a2937cf.png)

thanks for your help!

**Comment by PawelSuwinski** [comment]
Autocompletion: 
- https://api-platform.com/docs/admin/handling-relations/#using-an-autocomplete-input-for-relations

Default values: 
- https://marmelab.com/react-admin/Inputs.html#defaultvalue
- https://marmelab.com/react-admin/Form.html#defaultvalues

**Comment by papppeter** [comment]
> Autocompletion:
> 
> * https://api-platform.com/docs/admin/handling-relations/#using-an-autocomplete-input-for-relations
> 
> Default values:
> 
> * https://marmelab.com/react-admin/Inputs.html#defaultvalue
> * https://marmelab.com/react-admin/Form.html#defaultvalues

Thank its a realy good direction. 

In this case auto generated admin cannot be used any more? It needs custom code all time.

**Comment by PawelSuwinski** [comment]
> In this case auto generated admin cannot be used any more? It needs custom code all time.

Not necessarily, customized and decorated are only some child components or selected props: https://api-platform.com/docs/admin/customizing/
