### ISSUE TITLE
recordRepresentation prop not working

### ISSUE THREAD

**Issue by KDederichs** [api-platform/admin#497]
**API Platform version(s) affected**: 3.4.3

**Description**  
According to https://marmelab.com/react-admin/Tutorial.html#handling-relationships there's a `recordRepresentation` that's used to display an actual readable name on linked resources.
You guys have the prop as well but it's doing nothing, so I'd say either get rid of it or implement it as well

**How to reproduce**  
Set `recordRepresentation` prop on `ResourceGuesser`, see that it's still the ID

**Comment by dany-loveevents** [comment]
Hi

I'm using "@api-platform/admin": "^3.4.7" in my project and recordRepresentation no working for my.

I would need this function, otherwise I'll have to modify it throughout the project.

Do you know if this is already fixed in more recent versions?

Thanks!

**Comment by fzaninotto** [comment]
Yes, it is fixed in api platform admin 4.0.
