### ISSUE TITLE
Non required fields required in admin ?

### ISSUE THREAD

**Issue by sushicodeur** [api-platform/admin#50]
Hello, 

I've got an entity with many non required fields.

It looks like the generated admin requires every fields and won't allow submission until we set a value for each field. 

Maybe the inputFactory could look at input.required property before setting a validate method which require a value ?

Thanks

**Comment by dleute** [comment]
I am having the same issue. Was this ever resolved?

**Comment by dleute** [comment]
Just wanted to update on this: I updated the admin interface to 0.2 and the core to dev-master and almost all my issues went away, including this one.
