### ISSUE TITLE
Select input not fulfilled with default response data

### ISSUE THREAD

**Issue by Syfele** [api-platform/admin#505]
**API Platform version(s) affected**: x.y.z
It is not about API Platform, it is about admin

**Description**  
User have a ManyToOne relation with country, I can create and show user with country, but in edit form, select are empty by default, and I have error saying 
`No route found for "GET http://localhost/api/[object%20Object]" (from "http://localhost:3000/")`
As in the picture below 

**How to reproduce**  
 App.js : 
```
<HydraAdmin layout={MyLayout} entrypoint={process.env.REACT_APP_API_ENTRYPOINT}>
<ResourceGuesser name="users" list={UsersList} show={UserShow} edit={EditUser} create={CreateUser}></ResourceGuesser>
```
CreateUser.js : ( WORKS FINE)
```
<CreateGuesser {...props}>
<InputGuesser label="Email Address" source="email" type="email" />
<InputGuesser source="firstname" />
<InputGuesser source="lastname" />
<ReferenceInput
        label="User country"
        source="country"
        reference="countries"
      >
        <SelectInput source="country" optionText="label" />
      </ReferenceInput>
</CreateGuesser
```
EditUser.js : 
```
<InputGuesser label="Email Address" source="email" type="email" />
<InputGuesser source="firstname" />
<InputGuesser source="lastname" />
<ReferenceInput source="country" reference="countries">
      <SelectInput label="User country" optionText="label" />
</ReferenceInput>
```
**In the edit page, email, firstname and lastname are fulfilled but not country and I have error message : ( WITH the list of countries in it )**  

Am I missing something ? or whats wrong please ? I have try [React admin - Selecting a Foreign Key](https://marmelab.com/react-admin/SelectInput.html#selecting-a-foreign-key)  with no result, It doubling user country option in the select  

**Additional Context**  
![Capture d’écran de 2023-05-26 14-08-35](https://github.com/api-platform/admin/assets/45661399/7c9a5b7e-e620-4a2c-87bf-68bef4503574)

Thanks for help

**Comment by alanpoulain** [comment]
Hello, have you read https://api-platform.com/docs/admin/handling-relations/?

**Comment by alanpoulain** [comment]
What you need to use depends of the response of the API (and in particular if your relation is embedded or not).
Could you paste a typical response of your API?

**Comment by alanpoulain** [comment]
Have you tried using the `InputGuesser` for `country`? It should work by default.

**Comment by Syfele** [comment]
I have the same error and in select options I have api/countries/id instead of labels
![Capture d’écran de 2023-06-02 09-28-19](https://github.com/api-platform/admin/assets/45661399/cb0e4cb8-d250-4250-9c2b-177f94f5eee8)
![Capture d’écran de 2023-06-02 09-28-44](https://github.com/api-platform/admin/assets/45661399/038e9262-6e3e-4462-bc50-22bfc0b9fb9f)

**Comment by Syfele** [comment]
Solution was to use "useEmbedded: false" in dataProvider definition, sorry it was me

**Comment by ameotoko** [comment]
In order to use it with `useEmbedded: true` you'd need to use dot notation in the source prop:

```jsx
<ReferenceInput source="country.@id" reference="countries">
      <SelectInput label="User country" optionText="label" />
</ReferenceInput>
```

The fetch request comes from `<ReferenceInput>`, and it seems to be using its `source` prop to build the URL. If your relations are embedded, then `country` is an object instead of an IRI string, and that's why the HTTP request is made to `http://localhost/api/[object%20Object]`.

It is a little strange that all this extra research is needed just to make it work with the default settings (`useEmbedded: true`).
