### ISSUE TITLE
Using the Schema.org Vocabulary

### ISSUE THREAD

**Issue by laurent-bientz** [api-platform/admin#524]
**API Platform version(s) affected**: 3.2.13

**Description**  

With the default `HydraAdmin`, according to the [documentation](https://api-platform.com/docs/admin/schema.org#emails-urls-and-identifiers), we can customize some fields automatically, unfortunately this has no effect on the admin field.

For example, with the schema type `#[ApiProperty(types: ['https://schema.org/email'])]`, I expect to get an `input type="email"`.

```html
<input 
	aria-invalid="false" 
	aria-describedby="email-helper-text" 
	id="email" 
	name="email" 
	type="text" 
	class="MuiInputBase-input MuiFilledInput-input MuiInputBase-inputSizeSmall css-1zuho2-MuiInputBase-input-MuiFilledInput-input" 
	value="your.email@domain.tld"
>
```

![image](https://github.com/api-platform/admin/assets/6093572/79d2d58c-c6d4-4d01-ad02-fba62936f23a)

Do I miss something or the documentation isn't up to date?

**How to reproduce**  
```php
#[ApiProperty(types: ['https://schema.org/email'])]
#[ORM\Column(length: 180, unique: true)]
#[Assert\NotNull]
#[Assert\Email]
#[Groups(['user-read', 'user-write', 'user-create'])]
private ?string $email = null;
```
**Possible Solution**  
No idea.

**Additional Context**  

This other [documentation](https://api-platform.com/docs/core/validation/#open-vocabulary-generated-from-validation-metadata) mentions that constraints are automatically "casted" into the correct schema.

I also have an `#[Assert\Email]` on my property but still a basic text input on admin.

My hydra:ApiDocumentation **https://localhost/docs.jsonld**

![image](https://github.com/api-platform/admin/assets/6093572/74b6573a-66ce-4e12-8889-a506b0f00e14)

**Comment by PawelSuwinski** [comment]
This will work as expected:
```
#[ApiProperty(iris: ['https://schema.org/email'])]
```
But yes, there is still some inconsistency between  admin and docs: https://github.com/api-platform/docs/pull/1660.
