### ISSUE TITLE
`history` prop is deprecated and will be removed in V5

### ISSUE THREAD

**Issue by adguernier** [api-platform/admin#533]
**Description**  
`<AdminGuesser>` [uses the `history` prop](https://github.com/api-platform/admin/blob/2eb9f9b4833acf53bc5c2d74e9a987c7377cc895/src/AdminGuesser.tsx#L184) which is deprecated since React-admin v4. 
Additionally, [this prop will be removed](https://github.com/marmelab/react-admin/pull/9657) in React-admin V5.

**Possible Solution**  
Remove this prop and let users [choose the history component they need](https://marmelab.com/react-admin/Upgrade.html#using-a-custom-history)

**Comment by PawelSuwinski** [comment]
Partially resolved by #537 . 

TODO: 

- [ ] remove history prop type
- [ ] add router prop (` router: RouterEl  = BrowserRouter`)

**Comment by fzaninotto** [comment]
`history` is no longer used in api-platform admin v4.
