### ISSUE TITLE
Implementation means I cannot set `actions` prop for the top toolbar

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/admin#546]
**API Platform version(s) affected**: 3.4.6

**Description**  
I have a requirement to change the export button functionality. While I could use the `exporter` prop, this still makes API requests from the data provider, and what I need is for the button to call a specific endpoint in the API to get a custom response. As recommended in the React Admin documentation I am trying this:
```
const ListActions = (props: any) => {
        return (
          <TopToolbar>
            {props.hasCreate !== false && <CreateButton/>}
            <FilterButton />
            <ExportButton/>
          </TopToolbar>
        );
      }
```

and

```
<ListGuesser {...props} exporter={false} actions={<ListActions />}>
```

But I am greeted with an error `Error: The <FilterButton> component requires the <List filters> prop to be set`

I'm not sure if this is related to the introspection. I can see a `props.filters` property in the parameter passed to `ListActions`

**How to reproduce**  
For a `ResourceGuesser` set the list where filters should be showing (and do if no custom actions are set)
```
const ListActions = (props: any) => {
        return (
          <TopToolbar>
            <FilterButton />
          </TopToolbar>
        );
      }
const MyList = (props: any) => (
        <ListGuesser {...props} exporter={false} actions={<ListActions />}>
)
...
<ResourceGuesser name="YOUR_NAME" list={UsersList} />
```

**Possible Solution**  
I'm not sure right now, not a front-end expert.

I think for now I may need to manually define the filters prop e.g.

```
const postFilters = [
        <TextInput name="My Name" label="Title" source="title" defaultValue="Hello, World!" />,
      ];

<ListGuesser {...props} exporter={false} actions={<ListActions />} filters={postFilters}>
```

I'm not sure why this would be though... I may need to try and work out what this manual configuration would be for the 2 lists I want to use it on

perhaps you could export the `FilterGuesser` in the package for me to use when defining the `ListGuesser` ?

**Additional Context**  
n/a

**Comment by PawelSuwinski** [comment]
> I'm not sure if this is related to the introspection. I can see a props.filters property in the parameter passed to ListActions

Its already completed Filter node not an array of filters, that's why FilterButton yields for filter prop. Remove '<FilterButton />' from actions, than guessed filters should be rendered (didn't testes, just based on code reading) or play with:

```
       const ListActions = ({hasCreate, filters: Filters }) => (
         <TopToolbar>
            {hasCreate && <CreateButton/>}
            <Filters />
            <ExportButton/>
          </TopToolbar>
        );
      
```

**Comment by silverbackdan** [comment]
Thanks @PawelSuwinski - I understand, thank you - I think I did render that component at one point during my testing and it was just blank space that showed up.

Right now with this:
```
const ListActions = ({ hasCreate, filters: Filters, exporter }: any) => {
        // console.log('props', props.filters)
        return (
          <TopToolbar>
            <Filters />
            {hasCreate && <CreateButton/>}
            <ExportButton onClick={exporter} />
          </TopToolbar>
        );
      }
```

I got this:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ListActions`.
```

But I'm sure I can get this error gon after a lunch break. Perhaps I tried to use `props.filters` as the `component` prop of `FilterButton` before so I'll just work out where my code is out to cause this error.

**Comment by silverbackdan** [comment]
So I've got back to where this was the case before, and by doing this it renders, but the buttons are out of line and the filters don't show anything.

```
const ListActions = ({ hasCreate, filters, exporter }: any) => {
        console.log('props', filters)
        return (
          <TopToolbar>
            {filters}
            {hasCreate !== false && <CreateButton/>}
            <ExportButton onClick={exporter} />
          </TopToolbar>
        );
      }
```

![Screenshot 2024-04-08 at 13 41 11](https://github.com/api-platform/admin/assets/25174262/9b7e6ad9-881e-43f0-b156-6232e7649ef8)

**Comment by PawelSuwinski** [comment]
Right, I misspelled, It should be as above:
```
// ...
   {filters}
```

**Comment by silverbackdan** [comment]
Thanks @PawelSuwinski - including the component like this just seems to create an empty space which misaligns the other buttons, see the screenshot above - any ideas? Perhaps the filters doesn't include the button UI rendering or something.. I feel I'm missing something and unsure if it's possible to implement..

**Comment by silverbackdan** [comment]
I can see that it creates the filters form, but then we still need to figure out how to trigger the filter form that was created. I can't seem to find documentation on the <Filter> node that's been used in this way in the react admin docs to work this one out.

**Comment by silverbackdan** [comment]
I've figured out that this works.. the form alignment when showing is a little off still for the boolean toggle to filter `hidden` (in my case).

```
const ListActions = ({ hasCreate, filters, exporter }: any) => {
        const FilterButton = React.cloneElement(filters, { context: 'button' })
        return (
          <TopToolbar>
            <div>
              {FilterButton}
            </div>
            {hasCreate !== false && <CreateButton/>}
            <ExportButton onClick={exporter}/>
          </TopToolbar>
        );
      }
```

I realised the `Filter` node you are using is part of material UI and has a context for rendering the button or form. It looks like it'd render the form by default and buy cloning it, I can set the context to render as a the button.

How does this look from a position of more expertise as I pretty much hacked my way to this solution?

**Comment by PawelSuwinski** [comment]
> How does this look from a position of more expertise as I pretty much hacked my way to this solution?
It is not a hack, just a react way how to render element with changed props.

**Comment by silverbackdan** [comment]
OK brill, thank you - I didn't know if it was a recommended / best practice way or I was making something up.

I'm a Vue developer on front-end usually so this is all a bit alien. Thanks for your help through this :)
