### ISSUE TITLE
violationKey in getSubmissionErrors is undefined / validation results in generic "Server communication error"

### ISSUE THREAD

**Issue by herndlm** [api-platform/admin#548]
**API Platform version(s) affected**: 3.2.20

@api-platform/admin@3.4.6
@api-platform/api-doc-parser@0.16.4

**Description**  

API validation errors result in generic "Server communication error" in react-admin

**How to reproduce**  

**Possible Solution**  

**Additional Context**  

Interestingly it seems to be still working with @api-platform/admin@3.4.5. What confuses me is that 3.4.6 claims to fix issues like these.

API response:
content-type: application/problem+json; charset=utf-8
body:
```json
{
  "@id": "\\/validation_errors\\/6b3befbc-2f01-4ddf-be21-b57898905284",
  "@type": "ConstraintViolationList",
  "status": 422,
  "violations": [
    {
      "propertyPath": "entitlements",
      "message": "At least one product must be selected if policy is \\u0022restricted\\u0022.",
      "code": "6b3befbc-2f01-4ddf-be21-b57898905284"
    }
  ],
  "detail": "entitlements: At least one product must be selected if policy is \\u0022restricted\\u0022.",
  "hydra:title": "An error occurred",
  "hydra:description": "entitlements: At least one product must be selected if policy is \\u0022restricted\\u0022.",
  "type": "\\/validation_errors\\/6b3befbc-2f01-4ddf-be21-b57898905284",
  "title": "An error occurred"
}
```

react-admin UI behaviour
![image](https://github.com/api-platform/admin/assets/5738896/d87422b4-e2c7-4bee-a532-ee0613bf4d34)

Step debugging with 3.4.5 where it works
![image](https://github.com/api-platform/admin/assets/5738896/28748a83-b9a6-437d-a6ef-056514cbc53c)

Step debugging with 3.4.6 where it doesn't work
![image](https://github.com/api-platform/admin/assets/5738896/ff692cc6-7547-4e2c-be46-0c2e135a7ace)

There seems to be something going on with the protocol/domain/port part in props or their values. I wonder if I misconfigured something, somewhere. Not sure, if related, but API platform's `rfc_7807_compliant_errors` is `true` and changing this doesn't change anything apparently.

Is this in any way useful, maybe to give me further tips at least how to debug? I can't create a simple producer at the moment unfortunately.

**Comment by papppeter** [comment]
3.4.5 works for me as expected with api platform 3.2, 3.3.2 tested.

@type, @id gets the extra prefix as @herndlm pictures shows

server response looks correct:
![image](https://github.com/api-platform/admin/assets/3380880/80dd145f-39cf-43ef-ac03-dafb121137e4)

getDocumentationUrlFromHeaders(headers) gives back full url to /api/docs.jsonld

**Comment by herndlm** [comment]
I unfortunately didn't find more time to further debug it yet :/ but looks like you found the issue and fix already @PawelSuwinski. thx!

**Comment by PawelSuwinski** [comment]
@herndlm and @pappeter thanks for test cases and for debugging.
