### ISSUE TITLE
Authentication Support not working (infinite redirects)

### ISSUE THREAD

**Issue by 29Hido** [api-platform/admin#550]
**API Platform version(s) affected**: 3.2

**Description**  
I have an application using api-platform where api routes are protected with lexik_jwt_authentication to require a Bearer token when accessing resources.

I tried to create an api-platform admin project to manage my API and added authentication support from the [documentation](https://api-platform.com/docs/admin/authentication-support/)
When I access my admin app, I'm stuck in a loop redirecting to the /login route
(The admin app is fully working when removing authentication verification from my Symfony app)

I've tried to whitelist `/api/docs` and `/api/contexts` routes in my Symfony access_control which fix the redirecting loop but I cant see /login anymore and still getting a 401.

**How to reproduce**  
A reproducer is available [here](https://github.com/29Hido/apip-admin-repoducer/)

**Comment by PawelSuwinski** [comment]
https://github.com/api-platform/admin/issues/549#issuecomment-2078117075

**Comment by 29Hido** [comment]
> [#549 (comment)](https://github.com/api-platform/admin/issues/549#issuecomment-2078117075)

Fixed it by using 3.4.5 version instead, will wait for 3.4.7.
