### ISSUE TITLE
Edit form error when skip_null_values = false in api platform configuration

### ISSUE THREAD

**Issue by hosseinsalemi** [api-platform/admin#563]
**API Platform version(s) affected**: 3.2.22

**Description**  
The submit edit form gives me an error:

`Cannot read properties of null (reading 'rawFile')`.

The creation form works without problems.

**How to reproduce**  
In `api_platform.yaml` configuration file set `skip_null_values` to false.

**Comment by PawelSuwinski** [comment]
See: #559
