### ISSUE TITLE
Support react-admin v5

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/admin#569]
**Description**

Support react-admin v5: https://marmelab.com/blog/2024/06/20/react-admin-v5.html

**Example**

https://github.com/api-platform/demo/pull/421

**Comment by fzaninotto** [comment]
Should be straightforward. I wanted to start working on it today but I'm struggling with the DX - storybook fails in the pwa container. Will look again next week.

**Comment by vincentchalamon** [comment]
@fzaninotto if you need any sandbox to test react-admin v5 with api-platform/admin in a project: https://github.com/api-platform/demo/pull/421
