### ISSUE TITLE
Adding Jwt authentification 

### ISSUE THREAD

**Issue by Superprogrameur59** [api-platform/admin#74]
Hi, i'm trying to implement jwt authentification to my admin system but i detected some troubles.
Following this documentation :  "https://api-platform.com/docs/admin/authentication-support", I have to open security on many url of my API like : 
    -"url_api/"
    -"url_api/docs.jsonld/"
    -"url_api/contexts/Entrypoint/"

Then the system works perfectly ( redicrection to login page, store and use a JWT ...), but it's a bit weird to open some routes, even if it's only documentation, of a securised API.

So i tried to follow this : "https://github.com/api-platform/admin/pull/51 ". In this case i can securise all routes of the API but after login Many To One and Many to Many relations are not supported.

Is it possible to combine both ways ?

Thanks a lot ;)

**Comment by thomas-obernberger** [comment]
push - i am having the same problem :) does anyone have an idea?
thanks!

**Comment by jalmeida-mct** [comment]
same here, code from that documentation page doesn't work with JWT tokens, but API authorise functionality works fine.

**Comment by sunglee** [comment]
Anyone have JWT Authentication working with the latest version? 

I posted more detailed in this issue comment.

https://github.com/api-platform/admin/issues/273#issuecomment-586034661
