### ISSUE TITLE
Admin uses [object%20Object] in URL

### ISSUE THREAD

**Issue by luchianenco** [api-platform/admin#76]
Hi, can you explain why admin component uses object in URL. This leads to an error, and no entity can be edited. Thanks

<img width="939" alt="screen shot 2018-01-07 at 12 29 59" src="https://user-images.githubusercontent.com/3841383/34649042-d5d7aac4-f3a6-11e7-991e-47e65c50b01b.png">

This is Users get request

<img width="1433" alt="screen shot 2018-01-07 at 12 34 46" src="https://user-images.githubusercontent.com/3841383/34649052-30294942-f3a7-11e7-9adc-e7bef2d6a985.png">

and my User entity:

```
/**
 * User Entity
 * @ApiResource(
 *   collectionOperations={
 *     "get"={"method"="GET"},
 *     "post"={"route_name"="api_users_post_collection"}
 *   },
 *   itemOperations={
 *     "get"={"method"="GET"},
 *   },
 *   attributes={
 *     "normalization_context"={"groups"={"read"}},
 *     "denormalization_context"={"groups"={"write"}}
 *   }
 * )
 * @ORM\Entity
 */
class User implements UserInterface, \Serializable
```

**Comment by comxd** [comment]
Do you find a solution? I also encountered this problem, which occurs when I use a group serializer (@see api-platform/core).

With a group serializer, the returned context does not have the @context element:

```php
...
@ORM\Entity
 * @ApiResource(iri="http://schema.org/Organization", attributes={
 *         "normalization_context"={"groups"={"organization_read"}},
 *         "denormalization_context"={"groups"={"organization_write"}}
 *     })
...
```

@context with serialisation groups enabled:
```json
"@context": {
"@vocab": "http://domain.io/app_dev.php/docs.jsonld#",
"hydra": "http://www.w3.org/ns/hydra/core#",
"email": "http://schema.org/email",
"name": "http://schema.org/name",
"location": {
    "@id": "http://schema.org/location",
    "@type": "@id"
},
```

@context with serialisation groups disabled:
```json
"@context": {
"@vocab": "http://domain.io/app_dev.php/docs.jsonld#",
"hydra": "http://www.w3.org/ns/hydra/core#",
"email": "http://schema.org/email",
"name": "http://schema.org/name",
"location": "http://schema.org/location",
```

**Comment by luchianenco** [comment]
Unfortunately no

**Comment by comxd** [comment]
Related to #35

**Comment by brunoric** [comment]
Hi, I have the same issue. Seems related with normalization groups as said in #35.
