### ISSUE TITLE
Json-Ld to Json

### ISSUE THREAD

**Issue by marcinbis92** [api-platform/admin#77]
Hi guys, its possible to change request json-ld => json? I have problem with ids and urls.
When I use only json this fix my issue.

Using api-platform + admin

**Comment by mauchede** [comment]
Hello @marcinbis92,

Can you explained your problem with `application/ld+json` and `application/json`?

By the way, to define the default format, you have two solutions:
* configure your api-platform application (see https://api-platform.com/docs/core/content-negotiation#enabling-several-formats and https://api-platform.com/docs/core/configuration (section `formats`)).

***OR***

* configure your `hydraClient` in your admin application (see https://github.com/mauchede/example-api-platform-admin/blob/react-scripts/security/src/services/rest-client.js#L4)

**Comment by Simperfit** [comment]
If you have any more errors please feel free to ping me. This seems to be outdated.
