### ISSUE TITLE
Get resource  (using token)   without id of resource

### ISSUE THREAD

**Issue by mbdax034** [api-platform/admin#79]
Hello,
Api-platform need's an id but i want use the token to retreive the curent user.
How can'i do it?

Thanks

**Comment by mauchede** [comment]
Hello @mbdax034,

It looks like your question is about `api-platform/core`. You should ask it in the good repository or in [Symfony Slack](https://symfony.com/community) (channel `api-platform`).

I think the "easier" way to do something like this, is to [create a listener](https://api-platform.com/docs/core/events/#the-event-system) in your API:
* if `user` field has been defined -> nothing to do.
* if `user` field has not been defined -> you will initialize the field with the current user.
