### ISSUE TITLE
Create and Edit button doesn't work : "RangeError: Maximum call stack in ReactCompositeComponent.js:793"

### ISSUE THREAD

**Issue by riwanab** [api-platform/admin#82]
When I click on "Create" or "Edit" on Chrome on  Ubuntu, I got this error : "RangeError: Maximum call stack in ReactCompositeComponent.js:793"

I did a fresh install with https://github.com/api-platform/api-platform/releases/tag/v2.2.0
but the 2 buttons not working.

I update my package.json to this value : https://github.com/api-platform/api-platform/blob/master/admin/package.json
but the 2 buttons not working again :(

Someone has an idea or the same problem ?

![api_platform_admin_react_error](https://user-images.githubusercontent.com/12944040/36599695-85a1b70a-18b0-11e8-9745-48d3a9dfeaca.png)

**Comment by dunglas** [comment]
Fixed by https://github.com/api-platform/api-platform/pull/582.
You can just update your dependencies l’île in the linked patch.

**Comment by riwanab** [comment]
Yes I mentionned that I updated my dependenties but still bugging :(

**Comment by mauchede** [comment]
Hello @riwanab,

As @dunglas said, the project has been updated. Your `package.json` should now look like:

```js
{
  "dependencies": {
    "@api-platform/admin": "^0.3.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "react-scripts": "^1.1.0"
  },
  ...
}
```

**Comment by riwanab** [comment]
Hello @mauchede,

Thanks for you reply.

I updated the package.json of the admin folder but still got the error.

**Comment by mauchede** [comment]
It is strange... Can you:
* remove `node_modules` and `yarn.lock` and install dependencies.
* be sure your browser does not keep in cache your "old" JS.

If you still have an issue, can you post here your `yarn.lock`?

**Comment by riwanab** [comment]
I had the bug when I was using https://github.com/api-platform/api-platform/releases/tag/v2.2.0 to get the admin code.

I test to get the admin code with this link https://api-platform.com/docs/admin/getting-started and it works !

Maybe I did something wrong with the code, dunno...

**Comment by riwanab** [comment]
Very strange :
I get the **admin code** from https://api-platform.com/docs/admin/getting-started and it works.
I get the **Dockerfile** and**docker-compose.yaml** from https://github.com/api-platform/api-platform/releases/tag/v2.2.0

When I let the word "admin" in **Dockerfile**  and **docker-compose.yaml** there is the bug with create/edit button.
When I rename the word "admin" with "myadmin" in **Dockerfile**  and **docker-compose.yaml**, it works...

**Comment by riwanab** [comment]
Maybe it's the **registerServiceWorker.js** that save javascript code.

**Comment by mauchede** [comment]
The fix is available in `v2.2.2` (see https://github.com/api-platform/api-platform/releases/tag/v2.2.2).

So you have to:
* update your project.
* rebuild `admin` image to update `node_modules` (`docker-compose build admin`).

**Comment by riwanab** [comment]
@mauchede 
When you say :
> update your project
There is a command for this ?

**Comment by mauchede** [comment]
* If your `git` remote is always `api-platform/api-platform`, checkout the tag `v2.2.2` (`git checkout -f v2.2.2`).
* Otherwise, check if your `package.json` and `yarn.lock` look like the `api-platform/api-platform` files (see [package.json](https://github.com/api-platform/api-platform/blob/master/admin/package.json) and [yarn.lock](https://github.com/api-platform/api-platform/blob/master/admin/yarn.lock)).

Do not forget to rebuild the admin image (`docker-compose build admin`) after any changes on these files. After a build, you have the remove the container and create a new one (restart is not enough):

```sh
docker-compose rm -fsv admin
docker-compose build
docker-compose up -d
```

**Comment by riwanab** [comment]
@mauchede Thanks a lot ! It works perfectly !
(I just add "sudo" before all commands)
