### ISSUE TITLE
Difference between ADMIN vs CLIENT (in React) ?

### ISSUE THREAD

**Issue by riwanab** [api-platform/admin#85]
Hello,
I just want to know the difference in api-platform between **ADMIN** part in React and the **CLIENT** part in React (except that one use Material Design, the other Bootstrap and that ADMIN is generated dynamically, CLIENT need command to generate) ?

Thanks !

**Comment by dunglas** [comment]
Admin is dynamic, and is designed to build back-offices.
Client is generated, is designed to be edited, and best suit front-offices.

**Comment by riwanab** [comment]
Perfect thanks !
