### ISSUE TITLE
Autocomplete on ManyToOne relations?

### ISSUE THREAD

**Issue by Mattin** [api-platform/admin#90]
Hello,

I have ManyToOne relations with lot of options and in admin there's problem that not all options are in list (only first 30). Is there a easy way to use same component as on OneToMany relations with autocomplete/search functionality?

Thanks.

**Comment by Mattin** [comment]
Nevermind, I figure it out :).

**Comment by trsteel88** [comment]
@Mattin are you able to tell me the solution you found for this?

**Comment by Mattin** [comment]
@trsteel88 Well you need to override hydra generated config and add `filterToQuery` to `<ReferenceInput>`. Plus in api-platform entites set `@ApiFilter(SearchFilter::class)` to field you want to filter. Here is example (resource is meals, field with autocomplete is vendor).

```
const { fields } = resources.find(({ name }) => 'meals' === name);

// Vendor field
const fieldVendor = fields.find(({ name }) => 'vendor' === name);
const fieldInputVendor = (props) => (
    <ReferenceInput label='Vendor' source='vendor' key="vendor" reference='vendors' {...props} filterToQuery={searchText => ({ name: searchText })} allowEmpty={true}>
        <AutocompleteInput optionText='name' {...props} />
    </ReferenceInput>
);
fieldInputVendor.defaultProps = {
    addField: true,
    addIdField: true
};

fieldVendor.input = fieldInputVendor;
```
