### ISSUE TITLE
'name conversion' and admin component issue

### ISSUE THREAD

**Issue by stahoos** [api-platform/admin#93]
When I turn on `name_convertion` to `name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'` as documentation says (https://api-platform.com/docs/core/serialization#name-conversion), in api response I see properies like that: `person_name`, instead defined in entity: `personName` but admin component won't show that fields:(

When I turned off, in api response I see `personName` and admin comnponent show that fields

where/or how I can configure admin to show that fields?

**Comment by mauchede** [comment]
Hello @stahoos,

It does not seem to be a problem with `api-platform/admin`. Documentation generated by `api-platform` does not use the `name_converter`. We will fix this problem in `api-platform/core`.

**Comment by dunglas** [comment]
Fixed by api-platform/core#1919
